package cli_test

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/yasyf/cc-guides/internal/cli"
	"github.com/yasyf/cc-guides/lockfile"
)

func exec(args ...string) (code int, stdout, stderr string) {
	var out, errb bytes.Buffer
	code = cli.Execute(context.Background(), args, &out, &errb)
	return code, out.String(), errb.String()
}

func write(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil { // #nosec G304 G703 -- test writes under t.TempDir(), not an attacker path
		t.Fatal(err)
	}
}

// repo sets up a temp repo (with .git) and chdirs into it.
func repo(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, ".git"), 0o750); err != nil {
		t.Fatal(err)
	}
	t.Chdir(dir)
	return dir
}

// guidesFixture writes a local guides dir usable as a --source override.
func guidesFixture(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	write(t, filepath.Join(dir, "md", "ccx.md"), "## Compact Context\nccx body\n")
	write(t, filepath.Join(dir, "sh", "install.sh"), "#!/bin/sh\nNAME=\"{{binary}}\"\necho \"$NAME\"\n")
	write(t, filepath.Join(dir, "json", "settings-base.json"), "{\n  \"model\": \"opus\"\n}\n")
	return dir
}

// packFixture writes a pack checkout the way a real source repo is laid out: a
// cc-guides.toml at the root pointing at a nested guides dir.
func packFixture(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	write(t, filepath.Join(dir, ".claude", "cc-guides.toml"), "name = \"cc-skills\"\nguides = \"plugin/guides\"\n")
	guides := filepath.Join(dir, "plugin", "guides")
	write(t, filepath.Join(guides, "md", "ccx.md"), "## Compact Context\nccx body\n")
	write(t, filepath.Join(guides, "json", "settings-base.json"), "{\n  \"model\": \"opus\"\n}\n")
	return dir
}

// srcFlag builds the --source override for the local guides fixture.
func srcFlag(fixture string) string { return "cc-skills=" + fixture }

// ccSkillsSource is the [sources.cc-skills] table a layout that imports cc-skills
// must declare (there is no baked default); --source overrides its spec to the
// local fixture so tests stay offline.
const ccSkillsSource = "\n[sources.cc-skills]\nsource = \"github:yasyf/cc-skills@main\"\n"

// mdMarker/shMarker are the version-free generated markers a v3 render writes.
func mdMarker(dir string) string {
	return "<!-- GENERATED by cc-guides from " + dir + "/ — do not edit; edit the fragments and push — CI renders. -->"
}

func shMarker(dir string) string {
	return "# GENERATED by cc-guides from " + dir + "/ — do not edit; edit the fragments and push — CI renders."
}

// ymlMarker is the yaml artifact's marker — the shell `# ` comment form.
func ymlMarker(dir string) string { return shMarker(dir) }

func TestVersionExit(t *testing.T) {
	code, out, _ := exec("--version")
	if code != 0 || out != "dev\n" {
		t.Fatalf("version: code=%d out=%q", code, out)
	}
}

func TestRenderCheckV3RoundTrip(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\n  \"intro\",\n  \"cc-skills:ccx\",\n]\n"+ccSkillsSource)
	write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "# Repo\n\nIntro prose.\n")

	if code, _, errout := exec("render", "--source", srcFlag(fixture)); code != 0 {
		t.Fatalf("render exit = %d: %s", code, errout)
	}
	disk, err := os.ReadFile("AGENTS.md")
	if err != nil {
		t.Fatalf("artifact not written: %v", err)
	}
	s := string(disk)
	if firstLine(s) != mdMarker(".claude/fragments/AGENTS.md") {
		t.Fatalf("bad marker: %q", firstLine(s))
	}
	want := "# Repo\n\nIntro prose.\n\n## Compact Context\nccx body\n"
	if !strings.HasSuffix(s, want) {
		t.Fatalf("body:\n%s", s)
	}
	// The lock records the render, the artifact, and the (local) cc-skills pin.
	lock, err := os.ReadFile(".claude/fragments/cc-guides.lock")
	if err != nil {
		t.Fatalf("lock not written: %v", err)
	}
	for _, want := range []string{"schema = 1", `artifacts = ["AGENTS.md"]`, "[sources.cc-skills]", `commit = "local"`} {
		if !strings.Contains(string(lock), want) {
			t.Fatalf("lock missing %q:\n%s", want, lock)
		}
	}

	code, out, errout := exec("check", "--source", srcFlag(fixture))
	if code != 0 {
		t.Fatalf("check exit = %d: %s", code, errout)
	}
	if out != "OK\tAGENTS.md\n" {
		t.Fatalf("check out = %q", out)
	}
}

func TestCheckStaleAndMissing(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)

	// MISSING before render.
	if code, out, _ := exec("check", "--source", srcFlag(fixture)); code != 1 || out != "MISSING\tAGENTS.md\n" {
		t.Fatalf("missing: code=%d out=%q", code, out)
	}
	if code, _, _ := exec("render", "--source", srcFlag(fixture)); code != 0 {
		t.Fatal("render failed")
	}
	// Corrupt the body -> STALE.
	disk, _ := os.ReadFile("AGENTS.md")
	write(t, "AGENTS.md", string(disk)+"tampered\n")
	if code, out, _ := exec("check", "--source", srcFlag(fixture)); code != 1 || out != "STALE\tAGENTS.md\n" {
		t.Fatalf("stale: code=%d out=%q", code, out)
	}
}

// Cross-version: an artifact rendered by one binary version checks OK under a
// different one — the marker is version-free and check reproduces the body from
// the lock's pins, never a version token. The lock's version is pure provenance.
func TestCheckSelfPinningCrossVersion(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)

	if code, _, errout := exec("render", "--source", srcFlag(fixture)); code != 0 {
		t.Fatalf("render exit = %d: %s", code, errout)
	}
	disk, _ := os.ReadFile("AGENTS.md")
	if firstLine(string(disk)) != mdMarker(".claude/fragments/AGENTS.md") {
		t.Fatalf("marker must be version-free: %q", firstLine(string(disk)))
	}
	// Rewrite only the lock's provenance version: check must ignore it (the body
	// reproduces from the pins, no version compare) and never false-STALE.
	lockPath := ".claude/fragments/cc-guides.lock"
	lock, _ := os.ReadFile(lockPath)
	rewritten := strings.Replace(string(lock), `version = "dev"`, `version = "9.9.9"`, 1)
	if rewritten == string(lock) {
		t.Fatalf("expected a dev version to rewrite:\n%s", lock)
	}
	write(t, lockPath, rewritten)
	if code, out, errout := exec("check", "--source", srcFlag(fixture)); code != 0 || out != "OK\tAGENTS.md\n" {
		t.Fatalf("cross-version check: code=%d out=%q err=%s", code, out, errout)
	}
}

// An artifact still carrying the pre-CI-render marker core is recognized as
// generated: render overwrites it (never refusing it as handwritten) and stamps
// the new marker.
func TestRenderOverwritesLegacyMarker(t *testing.T) {
	repo(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"intro\"]\n")
	write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "# Repo\n")
	legacy := "<!-- GENERATED by cc-guides from .claude/fragments/AGENTS.md/ — do not edit; edit the fragments and run 'cc-guides render'. -->"
	write(t, "AGENTS.md", legacy+"\n# stale body\n")

	if code, _, errout := exec("render"); code != 0 {
		t.Fatalf("render must overwrite a legacy-marker artifact: code=%d err=%s", code, errout)
	}
	disk, _ := os.ReadFile("AGENTS.md")
	if firstLine(string(disk)) != mdMarker(".claude/fragments/AGENTS.md") {
		t.Fatalf("render must stamp the new marker, got %q", firstLine(string(disk)))
	}
}

// A layout with only local fragments (no imports) writes a marker and a lock with
// no source tables.
func TestRenderFragmentsNone(t *testing.T) {
	repo(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"intro\"]\n")
	write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "# Repo\n\nOnly local prose.\n")
	if code, _, errout := exec("render"); code != 0 {
		t.Fatalf("render exit = %d: %s", code, errout)
	}
	disk, _ := os.ReadFile("AGENTS.md")
	if firstLine(string(disk)) != mdMarker(".claude/fragments/AGENTS.md") {
		t.Fatalf("marker missing: %q", firstLine(string(disk)))
	}
	lock, _ := os.ReadFile(".claude/fragments/cc-guides.lock")
	if strings.Contains(string(lock), "[sources.") {
		t.Fatalf("import-free layout must lock no sources:\n%s", lock)
	}
	if code, out, _ := exec("check"); code != 0 || out != "OK\tAGENTS.md\n" {
		t.Fatalf("check: code=%d out=%q", code, out)
	}
}

func TestRenderShellArtifactWithArgs(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/plugin/scripts/install.sh/layout.toml",
		"fragments = [ { use = \"cc-skills:install\", args = { binary = \"slop-cop\" } } ]\n"+ccSkillsSource)

	if code, _, errout := exec("render", "--source", srcFlag(fixture)); code != 0 {
		t.Fatalf("render exit = %d: %s", code, errout)
	}
	disk, err := os.ReadFile("plugin/scripts/install.sh")
	if err != nil {
		t.Fatal(err)
	}
	lines := strings.Split(string(disk), "\n")
	if lines[0] != "#!/bin/sh" {
		t.Fatalf("line 1 = %q, want shebang", lines[0])
	}
	if lines[1] != shMarker(".claude/fragments/plugin/scripts/install.sh") {
		t.Fatalf("line 2 = %q, want marker", lines[1])
	}
	if !strings.Contains(string(disk), `NAME="slop-cop"`) {
		t.Fatalf("substitution missing:\n%s", disk)
	}
	info, _ := os.Stat("plugin/scripts/install.sh")
	if info.Mode().Perm()&0o111 == 0 {
		t.Errorf("new .sh artifact must be executable, mode=%v", info.Mode().Perm())
	}
	if code, out, errout := exec("check", "--source", srcFlag(fixture)); code != 0 {
		t.Fatalf("check exit=%d out=%q err=%s", code, out, errout)
	}
}

func TestDiscoveryGuardStrayFile(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"intro\"]\n")
	write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "# I\n")
	write(t, ".claude/fragments/AGENTS.md/stray.txt", "junk\n")
	code, _, errout := exec("render", "--source", srcFlag(fixture))
	if code != 2 || !strings.Contains(errout, "stray file") {
		t.Fatalf("code=%d err=%q, want stray file error", code, errout)
	}
}

func TestDiscoveryGuardUnreferencedFragment(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"intro\"]\n")
	write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "# I\n")
	write(t, ".claude/fragments/AGENTS.md/orphan.fragment.md", "dropped\n")
	code, _, errout := exec("render", "--source", srcFlag(fixture))
	if code != 2 || !strings.Contains(errout, "not referenced") {
		t.Fatalf("code=%d err=%q, want unreferenced error", code, errout)
	}
}

func TestDiscoveryGuardMissingLocalFragment(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"intro\"]\n")
	code, _, errout := exec("render", "--source", srcFlag(fixture))
	if code != 2 || !strings.Contains(errout, "do not exist") {
		t.Fatalf("code=%d err=%q, want missing-file error", code, errout)
	}
}

func TestDiscoveryGuardNestedSubdir(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)
	write(t, ".claude/fragments/AGENTS.md/nested/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)
	code, _, errout := exec("render", "--source", srcFlag(fixture))
	if code != 2 || !strings.Contains(errout, "flat") {
		t.Fatalf("code=%d err=%q, want flatness error", code, errout)
	}
}

func TestHandwrittenOverwriteRefused(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)
	write(t, "AGENTS.md", "handwritten, no marker\n")
	code, _, errout := exec("render", "--source", srcFlag(fixture))
	if code != 2 || !strings.Contains(errout, "handwritten") {
		t.Fatalf("code=%d err=%q", code, errout)
	}
	if code, _, _ := exec("render", "--source", srcFlag(fixture), "--force"); code != 0 {
		t.Fatalf("--force exit = %d", code)
	}
}

// A legacy pre-lock banner no longer marks a file as managed: render refuses it
// like any handwritten file. Adopt via --force once; the lock then owns the
// target, so a plain re-render succeeds.
func TestRenderLegacyBannerNoLongerOverwritable(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)
	write(t, "AGENTS.md", "<!-- cc-guides 0.1.7 src=.claude/fragments/AGENTS.md fragments=local | GENERATED — do not edit -->\n## Compact Context\nccx body\n")
	code, _, errout := exec("render", "--source", srcFlag(fixture))
	if code != 2 || !strings.Contains(errout, "handwritten") {
		t.Fatalf("code=%d err=%q, want handwritten-overwrite refusal", code, errout)
	}
	if code, _, errout := exec("render", "--source", srcFlag(fixture), "--force"); code != 0 {
		t.Fatalf("--force adoption: code=%d err=%s", code, errout)
	}
	if code, _, errout := exec("render", "--source", srcFlag(fixture)); code != 0 {
		t.Fatalf("re-render after adoption: code=%d err=%s", code, errout)
	}
}

func TestLint(t *testing.T) {
	dir := t.TempDir()
	write(t, filepath.Join(dir, "md", "ok.md"), "## Clean\nbody\n")
	write(t, filepath.Join(dir, "sh", "ok.sh"), "#!/bin/sh\necho hi\n")
	if code, _, _ := exec("lint", dir); code != 0 {
		t.Fatalf("clean lint exit = %d", code)
	}
	// A CRLF fragment reddens the gate.
	write(t, filepath.Join(dir, "md", "bad.md"), "line\r\nbody\n")
	code, _, errout := exec("lint", dir)
	if code != 1 || !strings.Contains(errout, "CRLF") {
		t.Fatalf("dirty lint: code=%d err=%q", code, errout)
	}
}

func TestLintShellMustHaveShebang(t *testing.T) {
	dir := t.TempDir()
	write(t, filepath.Join(dir, "sh", "noshebang.sh"), "echo hi\n")
	code, _, errout := exec("lint", dir)
	if code != 1 || !strings.Contains(errout, "shebang") {
		t.Fatalf("code=%d err=%q", code, errout)
	}
}

// A README.md at the pack root is documentation, not a fragment: it must not
// redden the gate even sitting next to real fragments.
func TestLintPackRootReadme(t *testing.T) {
	dir := t.TempDir()
	write(t, filepath.Join(dir, "README.md"), "# The Pack\n\nHumans read this.\n")
	write(t, filepath.Join(dir, "md", "ok.md"), "## Clean\nbody\n")
	write(t, filepath.Join(dir, "sh", "ok.sh"), "#!/bin/sh\necho hi\n")
	if code, _, errout := exec("lint", dir); code != 0 {
		t.Fatalf("pack-root README lint: code=%d err=%s", code, errout)
	}
}

// A README.md below the pack root (e.g. under md/) is rejected so it can never
// be resolved as the fragment named "README".
func TestLintReadmeUnderKindDirRejected(t *testing.T) {
	dir := t.TempDir()
	write(t, filepath.Join(dir, "md", "README.md"), "## Not\nbody\n")
	code, _, errout := exec("lint", dir)
	if code != 1 || !strings.Contains(errout, "reserved documentation") {
		t.Fatalf("md/README.md lint: code=%d err=%q", code, errout)
	}
}

// The README reservation is case-folded: a case variant in a kind dir (which a
// case-insensitive filesystem could resolve as the fragment named "README") is
// rejected, while a case variant at the pack root stays exempt documentation.
func TestLintReadmeCaseFold(t *testing.T) {
	for _, name := range []string{"README.MD", "readme.md"} {
		dir := t.TempDir()
		write(t, filepath.Join(dir, "md", name), "## Not\nbody\n")
		code, _, errout := exec("lint", dir)
		if code != 1 || !strings.Contains(errout, "reserved documentation") {
			t.Fatalf("md/%s lint: code=%d err=%q", name, code, errout)
		}
		// The same case variant at the pack root is legitimate documentation.
		rootDir := t.TempDir()
		write(t, filepath.Join(rootDir, name), "# The Pack\n\nHumans read this.\n")
		write(t, filepath.Join(rootDir, "md", "ok.md"), "## Clean\nbody\n")
		if code, _, errout := exec("lint", rootDir); code != 0 {
			t.Fatalf("pack-root %s lint: code=%d err=%s", name, code, errout)
		}
	}
}

// A kind dir must sit DIRECTLY under the pack root. A nested kind dir (e.g.
// nested/json/x.json) lints green under a naive immediate-parent check yet is
// unreachable — the resolver only reads <pack>/<kind>/<name><ext> — so it is
// rejected.
func TestLintNestedKindDirRejected(t *testing.T) {
	dir := t.TempDir()
	write(t, filepath.Join(dir, "nested", "json", "settings-base.json"), "{\"a\": 1}\n")
	code, _, errout := exec("lint", dir)
	if code != 1 || !strings.Contains(errout, "directly under the pack root") {
		t.Fatalf("nested kind dir lint: code=%d err=%q", code, errout)
	}
}

func TestCatImportAndLocal(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	code, out, _ := exec("cat", "--source", srcFlag(fixture), "cc-skills:ccx")
	if code != 0 || !strings.HasPrefix(out, "## Compact Context") {
		t.Fatalf("cat import: code=%d out=%q", code, firstLine(out))
	}
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"intro\"]\n")
	write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "# Local Intro\nbody\n")
	code, out, _ = exec("cat", "intro")
	if code != 0 || !strings.HasPrefix(out, "# Local Intro") {
		t.Fatalf("cat local: code=%d out=%q", code, firstLine(out))
	}
	if code, _, _ := exec("cat", "--source", srcFlag(fixture), "cc-skills:nonesuch"); code != 2 {
		t.Fatalf("unknown import exit = %d, want 2", code)
	}
}

// cat must refuse a traversal-shaped import name: `cc-skills:../README` once
// escaped the kind dir via filepath.Join normalization and printed the pack-root
// README instead of erroring.
func TestCatImportRejectsTraversalName(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, filepath.Join(fixture, "README.md"), "secret pack readme\n")
	code, out, errout := exec("cat", "--source", srcFlag(fixture), "cc-skills:../README")
	if code != 2 {
		t.Fatalf("traversal import exit = %d, want 2 (err=%q)", code, errout)
	}
	if strings.Contains(out, "secret") {
		t.Fatalf("traversal import leaked the pack-root README: %q", out)
	}
}

func TestList(t *testing.T) {
	repo(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"intro\", \"cc-skills:ccx\"]\n"+ccSkillsSource)
	write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "# I\n")
	code, out, _ := exec("list")
	if code != 0 {
		t.Fatalf("list exit = %d", code)
	}
	if !strings.Contains(out, "AGENTS.md\tmd\tintro,cc-skills:ccx") {
		t.Fatalf("list out = %q", out)
	}
}

func TestNoUnitsNotice(t *testing.T) {
	repo(t)
	code, out, errout := exec("render")
	if code != 0 || out != "" || !strings.Contains(errout, "no artifact dirs") {
		t.Fatalf("code=%d out=%q err=%q", code, out, errout)
	}
}

func TestUnknownCommandExit2(t *testing.T) {
	repo(t)
	if code, _, _ := exec("frobnicate"); code != 2 {
		t.Fatalf("exit = %d, want 2", code)
	}
}

// #2: a LOCAL entry declaring args must be token-substituted with two-way strictness.
func TestRenderLocalFragmentArgs(t *testing.T) {
	repo(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [ { use = \"intro\", args = { name = \"repo\" } } ]\n")
	write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "Hello {{name}}.\n")
	if code, _, errout := exec("render"); code != 0 {
		t.Fatalf("render exit = %d: %s", code, errout)
	}
	disk, _ := os.ReadFile("AGENTS.md")
	if !strings.Contains(string(disk), "Hello repo.") || strings.Contains(string(disk), "{{name}}") {
		t.Fatalf("local args not substituted:\n%s", disk)
	}
}

func TestRenderLocalFragmentArgsStrict(t *testing.T) {
	repo(t)
	// An arg the local fragment never consumes must hard-error (two-way strictness).
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [ { use = \"intro\", args = { unused = \"x\" } } ]\n")
	write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "no tokens here\n")
	if code, _, errout := exec("render"); code != 2 || !strings.Contains(errout, "no matching {{token}}") {
		t.Fatalf("code=%d err=%q, want unused-arg error", code, errout)
	}
}

// #1: a whitespace-only local fragment is rejected, not rendered as stray blanks.
func TestRenderWhitespaceOnlyLocalFragmentRejected(t *testing.T) {
	repo(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"intro\", \"body\"]\n")
	write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "# Head\n")
	write(t, ".claude/fragments/AGENTS.md/body.fragment.md", " \n \n")
	if code, _, errout := exec("render"); code != 2 || !strings.Contains(errout, "whitespace-only") {
		t.Fatalf("code=%d err=%q, want whitespace-only error", code, errout)
	}
}

// A json layout dir deep-merges local json fragments, writes a marker-free
// artifact, registers it in the lock, and round-trips through check.
func TestRenderCheckJSON(t *testing.T) {
	repo(t)
	write(t, ".claude/fragments/.claude/settings.json/layout.toml", "fragments = [\"base\", \"extra\"]\n")
	write(t, ".claude/fragments/.claude/settings.json/base.fragment.json", "{\n  \"permissions\": {\n    \"allow\": [\"Read\"]\n  }\n}\n")
	write(t, ".claude/fragments/.claude/settings.json/extra.fragment.json", "{\n  \"permissions\": {\n    \"allow\": [\"Bash(go:*)\"]\n  },\n  \"model\": \"opus\"\n}\n")

	if code, _, errout := exec("render"); code != 0 {
		t.Fatalf("json render exit=%d: %s", code, errout)
	}
	disk, err := os.ReadFile(".claude/settings.json")
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(disk), "GENERATED") {
		t.Fatalf("json artifact must carry no marker:\n%s", disk)
	}
	want := "{\n  \"permissions\": {\n    \"allow\": [\n      \"Read\",\n      \"Bash(go:*)\"\n    ]\n  },\n  \"model\": \"opus\"\n}\n"
	if string(disk) != want {
		t.Fatalf("merged json:\n%s\nwant:\n%s", disk, want)
	}
	lock, _ := os.ReadFile(".claude/fragments/cc-guides.lock")
	if !strings.Contains(string(lock), ".claude/settings.json") {
		t.Fatalf("lock must register the json artifact:\n%s", lock)
	}
	if code, out, errout := exec("check"); code != 0 || out != "OK\t.claude/settings.json\n" {
		t.Fatalf("json check: code=%d out=%q err=%s", code, out, errout)
	}
	// A byte change to the artifact is STALE.
	write(t, ".claude/settings.json", "{\n  \"model\": \"different\"\n}\n")
	if code, out, _ := exec("check"); code != 1 || out != "STALE\t.claude/settings.json\n" {
		t.Fatalf("json tamper: code=%d out=%q", code, out)
	}
}

// A json artifact importing a json fragment from a local source: the flattened
// fixture is the guides dir itself, while the pack fixture is a repo checkout the
// override must drill through its manifest to reach.
func TestRenderJSONImportFromLocalSource(t *testing.T) {
	for _, tc := range []struct {
		name    string
		fixture func(*testing.T) string
	}{
		{"flattened", guidesFixture},
		{"pack checkout", packFixture},
	} {
		t.Run(tc.name, func(t *testing.T) {
			repo(t)
			fixture := tc.fixture(t)
			write(t, ".claude/fragments/.claude/settings.json/layout.toml", "fragments = [\n  \"cc-skills:settings-base\",\n  \"overrides\",\n]\n"+ccSkillsSource)
			write(t, ".claude/fragments/.claude/settings.json/overrides.fragment.json", "{\n  \"env\": {\n    \"X\": \"1\"\n  }\n}\n")

			if code, _, errout := exec("render", "--source", srcFlag(fixture)); code != 0 {
				t.Fatalf("render exit=%d: %s", code, errout)
			}
			disk, err := os.ReadFile(".claude/settings.json")
			if err != nil {
				t.Fatal(err)
			}
			want := "{\n  \"model\": \"opus\",\n  \"env\": {\n    \"X\": \"1\"\n  }\n}\n"
			if string(disk) != want {
				t.Fatalf("merged json:\n%s\nwant:\n%s", disk, want)
			}
			if code, out, errout := exec("check", "--source", srcFlag(fixture)); code != 0 || out != "OK\t.claude/settings.json\n" {
				t.Fatalf("check: code=%d out=%q err=%s", code, out, errout)
			}
		})
	}
}

// json has no marker, so the lock's artifact registry is the only clobber-safety
// mechanism: a handwritten target is refused, --force adopts it into the lock, and
// subsequent renders are then allowed.
func TestJSONHandwrittenClobberGuard(t *testing.T) {
	repo(t)
	write(t, ".claude/fragments/.claude/settings.json/layout.toml", "fragments = [\"base\"]\n")
	write(t, ".claude/fragments/.claude/settings.json/base.fragment.json", "{\n  \"model\": \"opus\"\n}\n")
	write(t, ".claude/settings.json", "{ \"handwritten\": true }\n")

	if code, _, errout := exec("render"); code != 2 || !strings.Contains(errout, "handwritten") {
		t.Fatalf("json clobber guard: code=%d err=%q", code, errout)
	}
	if code, _, errout := exec("render", "--force"); code != 0 {
		t.Fatalf("force render: code=%d err=%s", code, errout)
	}
	if code, _, errout := exec("render"); code != 0 {
		t.Fatalf("re-render after lock adopts the target: code=%d err=%s", code, errout)
	}
}

// A yaml target renders by concatenation with a `#`-comment marker and 0o644
// mode (no marker-free json path), discovers under a nested hidden workflow dir,
// and a byte change to the managed artifact is STALE.
func TestRenderCheckYAML(t *testing.T) {
	repo(t)
	target := ".github/workflows/docs.yml"
	dir := ".claude/fragments/" + target
	write(t, dir+"/layout.toml", "fragments = [\"head\", \"jobs\"]\n")
	write(t, dir+"/head.fragment.yml", "# a load-bearing comment\nname: Docs\non: push\n")
	write(t, dir+"/jobs.fragment.yml", "jobs:\n  build:\n    runs-on: ubuntu-latest\n")

	if code, _, errout := exec("render"); code != 0 {
		t.Fatalf("yaml render exit=%d: %s", code, errout)
	}
	disk, err := os.ReadFile(target)
	if err != nil {
		t.Fatal(err)
	}
	s := string(disk)
	if firstLine(s) != ymlMarker(dir) {
		t.Fatalf("bad yaml marker: %q", firstLine(s))
	}
	want := "# a load-bearing comment\nname: Docs\non: push\n\njobs:\n  build:\n    runs-on: ubuntu-latest\n"
	if !strings.HasSuffix(s, want) {
		t.Fatalf("body:\n%s", s)
	}
	if info, _ := os.Stat(target); info.Mode().Perm() != 0o644 {
		t.Errorf("yaml artifact must be 0o644, got %v", info.Mode().Perm())
	}
	if code, out, errout := exec("check"); code != 0 || out != "OK\t"+target+"\n" {
		t.Fatalf("yaml check: code=%d out=%q err=%s", code, out, errout)
	}
	// A byte change to the managed artifact (marker preserved) is STALE.
	write(t, target, s+"extra: junk\n")
	if code, out, _ := exec("check"); code != 1 || out != "STALE\t"+target+"\n" {
		t.Fatalf("yaml tamper: code=%d out=%q", code, out)
	}
}

func TestLintJSON(t *testing.T) {
	dir := t.TempDir()
	write(t, filepath.Join(dir, "json", "ok.json"), "{\n  \"a\": 1\n}\n")
	// {{token}} placeholders are tolerated, in a string or a value position.
	write(t, filepath.Join(dir, "json", "strtoken.json"), "{\n  \"p\": \"{{venv}}/x\"\n}\n")
	write(t, filepath.Join(dir, "json", "valtoken.json"), "{\n  \"count\": {{n}}\n}\n")
	if code, _, errout := exec("lint", dir); code != 0 {
		t.Fatalf("clean json lint: code=%d err=%s", code, errout)
	}
	// A non-object root reddens the gate.
	write(t, filepath.Join(dir, "json", "bad.json"), "[1, 2]\n")
	if code, _, errout := exec("lint", dir); code != 1 || !strings.Contains(errout, "object") {
		t.Fatalf("bad json lint: code=%d err=%q", code, errout)
	}
}

func TestLintYAML(t *testing.T) {
	good := t.TempDir()
	write(t, filepath.Join(good, "yml", "ok.yml"), "# comment\nname: CI\non: push\n")
	// {{token}} placeholders are tolerated, in a value or a whole-scalar position,
	// and distinct token keys stay distinct (alongside a literal key they could shadow).
	write(t, filepath.Join(good, "yml", "token.yml"), "python: \"{{venv}}/bin/python\"\ncount: {{n}}\n")
	write(t, filepath.Join(good, "yml", "tokenkeys.yml"), "{{key1}}: a\n{{key2}}: b\n0: c\n")
	if code, _, errout := exec("lint", good); code != 0 {
		t.Fatalf("clean yaml lint: code=%d err=%s", code, errout)
	}
	// Each impurity reddens the gate with its own message, in isolation.
	for _, tc := range []struct{ name, content, want string }{
		{"invalid yaml", "key: [unclosed\n", "YAML"},
		{"repeated token key", "{{k}}: a\n{{k}}: b\n", "YAML"},
		{"crlf", "name: CI\r\n", "CRLF"},
		{"double trailing newline", "name: CI\n\n", "exactly one trailing newline"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			write(t, filepath.Join(dir, "yml", "bad.yml"), tc.content)
			if code, _, errout := exec("lint", dir); code != 1 || !strings.Contains(errout, tc.want) {
				t.Fatalf("code=%d err=%q, want %q", code, errout, tc.want)
			}
		})
	}
}

// A marker'd artifact with no lock entry cannot be pinned — invalid input.
func TestCheckMarkerNoLockInvalid(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)
	write(t, "AGENTS.md", mdMarker(".claude/fragments/AGENTS.md")+"\n## Compact Context\nccx body\n")
	if code, _, errout := exec("check", "--source", srcFlag(fixture)); code != 2 || !strings.Contains(errout, "no cc-guides.lock") {
		t.Fatalf("marker-no-lock: code=%d err=%q", code, errout)
	}
}

// A partial lock routes per artifact: the locked target still checks OK, while a
// sibling absent from the (non-nil) lock is invalid input — there is no banner
// fallback anymore, so the repo must render to register it.
func TestCheckPartialLockPerArtifact(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)
	if code, _, errout := exec("render", "--source", srcFlag(fixture)); code != 0 {
		t.Fatalf("render: code=%d err=%s", code, errout)
	}
	// A sibling layout whose artifact carries a marker but has no lock entry.
	write(t, ".claude/fragments/CLAUDE.md/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)
	write(t, "CLAUDE.md", mdMarker(".claude/fragments/CLAUDE.md")+"\n## Compact Context\nccx body\n")

	code, out, errout := exec("check", "--source", srcFlag(fixture))
	if code != 2 {
		t.Fatalf("partial-lock check: code=%d out=%q err=%s, want 2", code, out, errout)
	}
	if !strings.Contains(out, "OK\tAGENTS.md") {
		t.Fatalf("locked artifact must still check OK, got %q", out)
	}
	if !strings.Contains(errout, "no cc-guides.lock entry") || !strings.Contains(errout, "CLAUDE.md") {
		t.Fatalf("unlocked sibling must be invalid input naming CLAUDE.md, got %q", errout)
	}
}

// check is a diagnostic, so every unloadable artifact dir surfaces in ONE run: the
// first must not abort the rest, or fixing N broken dirs would cost N invocations.
// A healthy sibling still reports its own row alongside them.
func TestCheckReportsEveryUnloadableDir(t *testing.T) {
	repo(t)
	// Two different load failures, plus a dir that renders and locks cleanly.
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"intro\"]\n")
	write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "# Repo\n")
	if code, _, errout := exec("render"); code != 0 {
		t.Fatalf("render: code=%d err=%s", code, errout)
	}
	write(t, ".claude/fragments/CLAUDE.md/layout.toml", "fragments = [\"intro\"]\n")
	write(t, ".claude/fragments/CLAUDE.md/intro.fragment.md", "# C\n")
	write(t, ".claude/fragments/CLAUDE.md/stray.txt", "junk\n")
	write(t, ".claude/fragments/notes.yml/layout.toml", "fragments = [\"missing\"]\n")

	code, out, errout := exec("check")
	if code != 2 {
		t.Fatalf("check: code=%d out=%q err=%q, want 2", code, out, errout)
	}
	// Whole lines, so the format is pinned too: a load error names its dir exactly
	// once (the error already leads with it — a second label would read
	// "cc-guides: <dir>: <dir>: …").
	for _, want := range []string{
		"cc-guides: .claude/fragments/CLAUDE.md: stray file \"stray.txt\" (an artifact dir holds only layout.toml and *.fragment.md files)\n",
		"cc-guides: .claude/fragments/notes.yml: layout.toml references local fragment file(s) that do not exist: missing.fragment.yml\n",
	} {
		if !strings.Contains(errout, want) {
			t.Fatalf("both load failures must surface in one run, each naming its dir once, missing %q:\n%s", want, errout)
		}
	}
	if out != "OK\tAGENTS.md\n" {
		t.Fatalf("a healthy sibling must still report its row, got %q", out)
	}
}

// The lock detects a spec that no longer matches the layout and demands a re-render.
func TestCheckStaleLock(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)
	if code, _, errout := exec("render", "--source", srcFlag(fixture)); code != 0 {
		t.Fatalf("render: code=%d err=%s", code, errout)
	}
	// Re-check WITHOUT the --source override: the effective spec (the manifest form
	// in the layout) no longer matches the lock's recorded local override spec.
	if code, _, errout := exec("check"); code != 2 || !strings.Contains(errout, "lock out of date") {
		t.Fatalf("stale lock: code=%d err=%q", code, errout)
	}
}

// A full render is authoritative: removing a layout dir and re-rendering under
// --prune rebuilds the lock so the removed target is pruned, which restores
// clobber-safety at that path (a later layout there cannot overwrite the leftover
// file without --force). --prune is what makes dropping it deliberate; the bare
// re-render refuses first, which TestRenderRefusesToDropLockedArtifact pins.
func TestFullRenderRebuildsLockPruningRemovedTarget(t *testing.T) {
	repo(t)
	write(t, ".claude/fragments/.claude/settings.json/layout.toml", "fragments = [\"base\"]\n")
	write(t, ".claude/fragments/.claude/settings.json/base.fragment.json", "{\n  \"model\": \"opus\"\n}\n")
	write(t, ".claude/fragments/extra.json/layout.toml", "fragments = [\"base\"]\n")
	write(t, ".claude/fragments/extra.json/base.fragment.json", "{\n  \"n\": 1\n}\n")
	if code, _, errout := exec("render"); code != 0 {
		t.Fatalf("render: code=%d err=%s", code, errout)
	}
	lock, _ := os.ReadFile(".claude/fragments/cc-guides.lock")
	if !strings.Contains(string(lock), "extra.json") {
		t.Fatalf("lock must register both targets:\n%s", lock)
	}
	// Remove the extra.json layout dir; its rendered artifact stays on disk.
	if err := os.RemoveAll(".claude/fragments/extra.json"); err != nil {
		t.Fatal(err)
	}
	if code, _, errout := exec("render", "--prune"); code != 0 {
		t.Fatalf("re-render: code=%d err=%s", code, errout)
	}
	lock2, _ := os.ReadFile(".claude/fragments/cc-guides.lock")
	if strings.Contains(string(lock2), "extra.json") {
		t.Fatalf("full render must prune the removed target from the lock:\n%s", lock2)
	}
	// The pruned target is no longer lock-registered, so a new layout at that path
	// cannot clobber the leftover json without --force.
	write(t, ".claude/fragments/extra.json/layout.toml", "fragments = [\"base\"]\n")
	write(t, ".claude/fragments/extra.json/base.fragment.json", "{\n  \"n\": 2\n}\n")
	if code, _, errout := exec("render"); code != 2 || !strings.Contains(errout, "handwritten") {
		t.Fatalf("clobber-safety must be restored after prune: code=%d err=%q", code, errout)
	}
}

// Renaming an artifact dir without adding the matching `target` key silently
// orphaned the real artifact: the rename rendered a NEW target, the rebuilt lock
// forgot the old one, and render exited 0. For a markerless kind (json) lock
// membership was the only record that the file was managed, so nothing could
// detect it afterwards. A full render now refuses, and the correct move — adding
// the `target` key — renders the original artifact from the renamed dir.
func TestRenderRefusesToDropLockedArtifact(t *testing.T) {
	repo(t)
	write(t, ".claude/fragments/.mcp.json/layout.toml", "fragments = [\"base\"]\n")
	write(t, ".claude/fragments/.mcp.json/base.fragment.json", "{\n  \"mcpServers\": {}\n}\n")
	if code, _, errout := exec("render"); code != 0 {
		t.Fatalf("baseline render: code=%d err=%s", code, errout)
	}

	// The migration move, with the `target` key forgotten.
	if err := os.Rename(".claude/fragments/.mcp.json", ".claude/fragments/mcp.json"); err != nil {
		t.Fatal(err)
	}
	code, _, errout := exec("render")
	if code != 2 || !strings.Contains(errout, "refusing to stop managing an artifact still on disk: .mcp.json") {
		t.Fatalf("renamed dir must refuse: code=%d err=%q", code, errout)
	}
	// Nothing moved: the lock still owns the real artifact and no wrong path exists.
	lock, _ := os.ReadFile(".claude/fragments/cc-guides.lock")
	if !strings.Contains(string(lock), `artifacts = [".mcp.json"]`) {
		t.Fatalf("a refused render must leave the lock intact:\n%s", lock)
	}
	if _, err := os.Stat("mcp.json"); !os.IsNotExist(err) {
		t.Fatal("a refused render must not write the wrong target")
	}
	// --dry-run reports the same refusal rather than a clean plan.
	if code, _, errout := exec("render", "--dry-run"); code != 2 || !strings.Contains(errout, "refusing to stop managing") {
		t.Fatalf("dry-run must surface the hazard: code=%d err=%q", code, errout)
	}
	// check must not certify the state either: the lock claims a target nothing renders.
	if code, out, _ := exec("check"); code != 1 || !strings.Contains(out, "ORPHANED\t.mcp.json\n") {
		t.Fatalf("check must report the orphan: code=%d out=%q", code, out)
	}

	// The correct move: the renamed dir names its target explicitly.
	write(t, ".claude/fragments/mcp.json/layout.toml", "target = \".mcp.json\"\n\nfragments = [\"base\"]\n")
	if code, _, errout := exec("render"); code != 0 {
		t.Fatalf("target key must fix it: code=%d err=%s", code, errout)
	}
	if code, out, _ := exec("check"); code != 0 || out != "OK\t.mcp.json\n" {
		t.Fatalf("after the fix: code=%d out=%q", code, out)
	}
	if _, err := os.Stat("mcp.json"); !os.IsNotExist(err) {
		t.Fatal("the wrong target must never exist")
	}
}

// A drop whose artifact is already gone from disk orphans nothing, so it needs no
// --prune: deleting the dir and its rendered file together is a complete removal.
func TestRenderDropWithFileGoneNeedsNoPrune(t *testing.T) {
	repo(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"intro\"]\n")
	write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "# Repo\n")
	write(t, ".claude/fragments/extra.json/layout.toml", "fragments = [\"base\"]\n")
	write(t, ".claude/fragments/extra.json/base.fragment.json", "{\n  \"n\": 1\n}\n")
	if code, _, errout := exec("render"); code != 0 {
		t.Fatalf("baseline render: code=%d err=%s", code, errout)
	}
	if err := os.RemoveAll(".claude/fragments/extra.json"); err != nil {
		t.Fatal(err)
	}
	if err := os.Remove("extra.json"); err != nil {
		t.Fatal(err)
	}
	if code, _, errout := exec("render"); code != 0 {
		t.Fatalf("a complete removal must not need --prune: code=%d err=%s", code, errout)
	}
	lock, _ := os.ReadFile(".claude/fragments/cc-guides.lock")
	if strings.Contains(string(lock), "extra.json") {
		t.Fatalf("the removed target must leave the lock:\n%s", lock)
	}
}

// A scoped render merges into the lock and prunes nothing, so it cannot drop a
// target and the guard must not fire on one.
func TestScopedRenderSkipsDropGuard(t *testing.T) {
	repo(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"intro\"]\n")
	write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "# Repo\n")
	write(t, ".claude/fragments/extra.json/layout.toml", "fragments = [\"base\"]\n")
	write(t, ".claude/fragments/extra.json/base.fragment.json", "{\n  \"n\": 1\n}\n")
	if code, _, errout := exec("render"); code != 0 {
		t.Fatalf("baseline render: code=%d err=%s", code, errout)
	}
	// Rendering only one dir leaves the other's target out of this run's batch.
	if code, _, errout := exec("render", ".claude/fragments/AGENTS.md"); code != 0 {
		t.Fatalf("scoped render must not trip the drop guard: code=%d err=%s", code, errout)
	}
	lock, _ := os.ReadFile(".claude/fragments/cc-guides.lock")
	if !strings.Contains(string(lock), "extra.json") {
		t.Fatalf("scoped render must preserve the untouched target:\n%s", lock)
	}
}

// A `target` carrying a raw newline once rendered at exit 0 and wrote a lock with a
// newline inside a TOML basic string, after which every render and check died with
// "strings cannot contain newlines" until someone repaired the lock by hand. The
// render must refuse, and — belt and braces at the serialization boundary — a lock
// written from such a value must still parse.
func TestTargetWithControlCharRefusedAndLockStaysParseable(t *testing.T) {
	repo(t)
	target := "ok.md\n[sources.evil]\nspec = \"pwned\"\nnote.md"
	write(t, ".claude/fragments/evil/layout.toml", "target = "+strconv.Quote(target)+"\n\nfragments = [\"base\"]\n")
	write(t, ".claude/fragments/evil/base.fragment.md", "# body\n")

	code, _, errout := exec("render")
	if code != 2 || !strings.Contains(errout, "unsafe target") {
		t.Fatalf("a control character in a target must be refused: code=%d err=%q", code, errout)
	}
	if _, err := os.Stat(lockfile.Path); !os.IsNotExist(err) {
		t.Fatal("a refused render must write no lock")
	}

	// The serializer must be safe on its own, so a value reaching it by any other
	// route still writes a lock that reads back.
	enc := (&lockfile.Lock{Schema: 1, Version: "1.2.3", Artifacts: []string{target}}).Encode()
	back, err := lockfile.Parse(enc)
	if err != nil {
		t.Fatalf("a lock holding %q must parse back, got %v:\n%s", target, err, enc)
	}
	if len(back.Artifacts) != 1 || back.Artifacts[0] != target {
		t.Fatalf("round-trip lost the artifact: %#v", back.Artifacts)
	}
}

// pr-check answers "did this PR touch a file it must not", which the lock alone
// decides; the dirs only sharpen the message. A broken artifact dir the PR never
// touched must not fail it — that would let one WIP dir on trunk block every
// unrelated PR across the fleet.
func TestPRCheckToleratesUnrelatedBrokenDir(t *testing.T) {
	dir := gitRepo(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"intro\"]\n")
	write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "# Repo\n")
	write(t, "AGENTS.md", "# Repo\n")
	write(t, lockfile.Path, prCheckBaseLock)
	// An unrelated dir that cannot load: a stray file makes loadArtifactDir fail.
	write(t, ".claude/fragments/wip.md/layout.toml", "fragments = [\"x\"]\n")
	write(t, ".claude/fragments/wip.md/x.fragment.md", "# wip\n")
	write(t, ".claude/fragments/wip.md/stray.txt", "junk\n")
	runGitT(t, dir, "add", "-A")
	runGitT(t, dir, "commit", "-q", "-m", "base")
	base := runGitT(t, dir, "rev-parse", "HEAD")

	write(t, "README_PR.md", "# unrelated\n")
	runGitT(t, dir, "add", "-A")
	runGitT(t, dir, "commit", "-q", "-m", "pr")

	code, stdout, stderr := exec("pr-check", base)
	if code != 0 || stdout != "cc-guides: no CI-owned artifact was hand-edited\n" {
		t.Fatalf("an unrelated broken dir must not fail a clean PR: code=%d stdout=%q stderr=%q", code, stdout, stderr)
	}
}

// Two dirs claiming one target is a repo-wide misconfiguration render and check both
// refuse; pr-check refuses it too rather than silently picking whichever dir the map
// happened to write last.
func TestPRCheckRefusesCollidingTargets(t *testing.T) {
	dir := gitRepo(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"intro\"]\n")
	write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "# Repo\n")
	write(t, "AGENTS.md", "# Repo\n")
	write(t, lockfile.Path, prCheckBaseLock)
	write(t, ".claude/fragments/agents/layout.toml", "target = \"AGENTS.md\"\n\nfragments = [\"intro\"]\n")
	write(t, ".claude/fragments/agents/intro.fragment.md", "# Other\n")
	runGitT(t, dir, "add", "-A")
	runGitT(t, dir, "commit", "-q", "-m", "base")
	base := runGitT(t, dir, "rev-parse", "HEAD")
	write(t, "README_PR.md", "# unrelated\n")
	runGitT(t, dir, "add", "-A")
	runGitT(t, dir, "commit", "-q", "-m", "pr")

	code, _, stderr := exec("pr-check", base)
	if code != 2 || !strings.Contains(stderr, "is shared by") {
		t.Fatalf("colliding targets must refuse: code=%d stderr=%q", code, stderr)
	}
}

// Targets differing only by case are one file on the case-insensitive filesystem the
// fleet authors on and two on the case-sensitive one CI renders on. Refusing in both
// places keeps a repo's render portable, and the message names each target since the
// dirs alone would read as two identical strings colliding.
func TestRenderRefusesCaseFoldedTargetCollision(t *testing.T) {
	repo(t)
	write(t, ".claude/fragments/notes.md/layout.toml", "fragments = [\"base\"]\n")
	write(t, ".claude/fragments/notes.md/base.fragment.md", "# a\n")
	write(t, ".claude/fragments/upper/layout.toml", "target = \"NOTES.md\"\n\nfragments = [\"base\"]\n")
	write(t, ".claude/fragments/upper/base.fragment.md", "# b\n")

	code, _, errout := exec("render")
	if code != 2 || !strings.Contains(errout, "is shared by") {
		t.Fatalf("case-folded collision must refuse: code=%d err=%q", code, errout)
	}
	for _, want := range []string{
		"NOTES.md (.claude/fragments/upper)",
		"notes.md (.claude/fragments/notes.md)",
		// Without the reason, a reader on case-sensitive Linux — where this layout
		// genuinely works — reads the refusal as a tool bug.
		"differing only by case: one file where authoring happens, two where CI renders",
	} {
		if !strings.Contains(errout, want) {
			t.Fatalf("message must name each target and the reason, missing %q:\n%s", want, errout)
		}
	}
}

// A same-case collision is the ordinary kind: it names the dirs and stays silent about
// case, which would only be noise.
func TestRenderSameCaseCollisionOmitsCaseReason(t *testing.T) {
	repo(t)
	write(t, ".claude/fragments/notes.md/layout.toml", "fragments = [\"base\"]\n")
	write(t, ".claude/fragments/notes.md/base.fragment.md", "# a\n")
	write(t, ".claude/fragments/other/layout.toml", "target = \"notes.md\"\n\nfragments = [\"base\"]\n")
	write(t, ".claude/fragments/other/base.fragment.md", "# b\n")

	code, _, errout := exec("render")
	if code != 2 || !strings.Contains(errout, `target "notes.md" is shared by .claude/fragments/notes.md, .claude/fragments/other`) {
		t.Fatalf("same-case collision: code=%d err=%q", code, errout)
	}
	if strings.Contains(errout, "differing only by case") {
		t.Fatalf("a same-case collision must not blame case:\n%s", errout)
	}
}

// An unreadable target (here a directory in the artifact's place) is a hard error
// in the preflight, never treated as absent — otherwise the lock would register it
// and a later retry would clobber it without --force.
func TestRenderUnreadableTargetErrorsBeforeLock(t *testing.T) {
	repo(t)
	write(t, ".claude/fragments/.claude/settings.json/layout.toml", "fragments = [\"base\"]\n")
	write(t, ".claude/fragments/.claude/settings.json/base.fragment.json", "{\n  \"model\": \"opus\"\n}\n")
	if err := os.MkdirAll(".claude/settings.json", 0o750); err != nil {
		t.Fatal(err)
	}
	if code, _, errout := exec("render"); code != 2 {
		t.Fatalf("unreadable target must be a hard error: code=%d err=%s", code, errout)
	}
	if _, err := os.Stat(".claude/fragments/cc-guides.lock"); !os.IsNotExist(err) {
		t.Fatal("a preflight failure must not write the lock (which would register the target)")
	}
}

// Two dirs whose effective targets collide — one path-derived, one from a `target`
// override — are refused in the preflight, before any artifact or lock is written.
func TestRenderTargetCollisionRefusedBeforeWrite(t *testing.T) {
	repo(t)
	write(t, ".claude/fragments/.gitignore/layout.toml", "fragments = [\"base\"]\n")
	write(t, ".claude/fragments/.gitignore/base.fragment.gitignore", "node_modules/\n")
	write(t, ".claude/fragments/gitignore/layout.toml", "target = \".gitignore\"\n\nfragments = [\"logs\"]\n")
	write(t, ".claude/fragments/gitignore/logs.fragment.gitignore", "*.log\n")

	code, _, errout := exec("render")
	if code != 2 || !strings.Contains(errout, `target ".gitignore" is shared by`) {
		t.Fatalf("colliding targets: code=%d err=%q", code, errout)
	}
	if _, err := os.Stat(".gitignore"); !os.IsNotExist(err) {
		t.Fatal("a refused batch must write no artifact")
	}
	if _, err := os.Stat(".claude/fragments/cc-guides.lock"); !os.IsNotExist(err) {
		t.Fatal("a refused batch must write no lock")
	}
}

// A path-scoped render is surgical: it merges into the lock, preserving artifacts
// it did not render (unlike a full render, which rebuilds and would drop them).
func TestScopedRenderMergesLock(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)
	write(t, ".claude/fragments/CLAUDE.md/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)
	if code, _, errout := exec("render", "--source", srcFlag(fixture)); code != 0 {
		t.Fatalf("full render: code=%d err=%s", code, errout)
	}
	lock, _ := os.ReadFile(".claude/fragments/cc-guides.lock")
	if !strings.Contains(string(lock), `"AGENTS.md"`) || !strings.Contains(string(lock), `"CLAUDE.md"`) {
		t.Fatalf("full render must register both:\n%s", lock)
	}
	if code, _, errout := exec("render", ".claude/fragments/AGENTS.md", "--source", srcFlag(fixture)); code != 0 {
		t.Fatalf("scoped render: code=%d err=%s", code, errout)
	}
	lock2, _ := os.ReadFile(".claude/fragments/cc-guides.lock")
	if !strings.Contains(string(lock2), `"CLAUDE.md"`) {
		t.Fatalf("scoped render must preserve the untouched artifact in the lock:\n%s", lock2)
	}
}

// A scoped render whose layout spec no longer matches the lock's recorded spec for
// a shared alias cannot pin safely — it must demand a full render.
func TestScopedRenderSpecDisagreementErrors(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	other := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)
	if code, _, errout := exec("render", "--source", srcFlag(fixture)); code != 0 {
		t.Fatalf("render: code=%d err=%s", code, errout)
	}
	code, _, errout := exec("render", ".claude/fragments/AGENTS.md", "--source", "cc-skills="+other)
	if code != 2 || !strings.Contains(errout, "full") {
		t.Fatalf("spec disagreement must demand a full render: code=%d err=%q", code, errout)
	}
}

func firstLine(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}
