package cli_test

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/yasyf/cc-guides/internal/cli"
)

func exec(args ...string) (code int, stdout, stderr string) {
	var out, errb bytes.Buffer
	code = cli.Execute(context.Background(), args, &out, &errb)
	return code, out.String(), errb.String()
}

func write(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil { // #nosec G304 G703 -- test writes under t.TempDir(), not an attacker path
		t.Fatal(err)
	}
}

// repo sets up a temp repo (with .git) and chdirs into it.
func repo(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, ".git"), 0o750); err != nil {
		t.Fatal(err)
	}
	t.Chdir(dir)
	return dir
}

// guidesFixture writes a local guides dir usable as a --source override.
func guidesFixture(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	write(t, filepath.Join(dir, "md", "ccx.md"), "## Compact Context\nccx body\n")
	write(t, filepath.Join(dir, "sh", "install.sh"), "#!/bin/sh\nNAME=\"{{binary}}\"\necho \"$NAME\"\n")
	return dir
}

// srcFlag builds the --source override for the local guides fixture.
func srcFlag(fixture string) string { return "cc-skills=" + fixture }

// ccSkillsSource is the [sources.cc-skills] table a layout that imports cc-skills
// must declare (there is no baked default); --source overrides its spec to the
// local fixture so tests stay offline.
const ccSkillsSource = "\n[sources.cc-skills]\nsource = \"github:yasyf/cc-skills@main\"\n"

// mdMarker/shMarker are the version-free generated markers a v3 render writes.
func mdMarker(dir string) string {
	return "<!-- GENERATED by cc-guides from " + dir + "/ — do not edit; edit the fragments and run 'cc-guides render'. -->"
}

func shMarker(dir string) string {
	return "# GENERATED by cc-guides from " + dir + "/ — do not edit; edit the fragments and run 'cc-guides render'."
}

func TestVersionExit(t *testing.T) {
	code, out, _ := exec("--version")
	if code != 0 || out != "dev\n" {
		t.Fatalf("version: code=%d out=%q", code, out)
	}
}

func TestRenderCheckV3RoundTrip(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\n  \"intro\",\n  \"cc-skills:ccx\",\n]\n"+ccSkillsSource)
	write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "# Repo\n\nIntro prose.\n")

	if code, _, errout := exec("render", "--source", srcFlag(fixture)); code != 0 {
		t.Fatalf("render exit = %d: %s", code, errout)
	}
	disk, err := os.ReadFile("AGENTS.md")
	if err != nil {
		t.Fatalf("artifact not written: %v", err)
	}
	s := string(disk)
	if firstLine(s) != mdMarker(".claude/fragments/AGENTS.md") {
		t.Fatalf("bad marker: %q", firstLine(s))
	}
	want := "# Repo\n\nIntro prose.\n\n## Compact Context\nccx body\n"
	if !strings.HasSuffix(s, want) {
		t.Fatalf("body:\n%s", s)
	}
	// The lock records the render, the artifact, and the (local) cc-skills pin.
	lock, err := os.ReadFile(".claude/fragments/cc-guides.lock")
	if err != nil {
		t.Fatalf("lock not written: %v", err)
	}
	for _, want := range []string{"schema = 1", `artifacts = ["AGENTS.md"]`, "[sources.cc-skills]", `commit = "local"`} {
		if !strings.Contains(string(lock), want) {
			t.Fatalf("lock missing %q:\n%s", want, lock)
		}
	}

	code, out, errout := exec("check", "--source", srcFlag(fixture))
	if code != 0 {
		t.Fatalf("check exit = %d: %s", code, errout)
	}
	if out != "OK\tAGENTS.md\n" {
		t.Fatalf("check out = %q", out)
	}
}

func TestCheckStaleAndMissing(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)

	// MISSING before render.
	if code, out, _ := exec("check", "--source", srcFlag(fixture)); code != 1 || out != "MISSING\tAGENTS.md\n" {
		t.Fatalf("missing: code=%d out=%q", code, out)
	}
	if code, _, _ := exec("render", "--source", srcFlag(fixture)); code != 0 {
		t.Fatal("render failed")
	}
	// Corrupt the body -> STALE.
	disk, _ := os.ReadFile("AGENTS.md")
	write(t, "AGENTS.md", string(disk)+"tampered\n")
	if code, out, _ := exec("check", "--source", srcFlag(fixture)); code != 1 || out != "STALE\tAGENTS.md\n" {
		t.Fatalf("stale: code=%d out=%q", code, out)
	}
}

// Cross-version: an artifact rendered by one binary version checks OK under a
// different one — the marker is version-free and check reproduces the body from
// the lock's pins, never a version token.
func TestCheckSelfPinningCrossVersion(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)

	if code, _, errout := exec("render", "--lock-version", "9.9.9", "--source", srcFlag(fixture)); code != 0 {
		t.Fatalf("render exit = %d: %s", code, errout)
	}
	disk, _ := os.ReadFile("AGENTS.md")
	if firstLine(string(disk)) != mdMarker(".claude/fragments/AGENTS.md") {
		t.Fatalf("marker must be version-free: %q", firstLine(string(disk)))
	}
	lock, _ := os.ReadFile(".claude/fragments/cc-guides.lock")
	if !strings.Contains(string(lock), `version = "9.9.9"`) {
		t.Fatalf("lock must record the render version:\n%s", lock)
	}
	// The running test binary is version "dev"; check must NOT false-STALE.
	if code, out, errout := exec("check", "--source", srcFlag(fixture)); code != 0 || out != "OK\tAGENTS.md\n" {
		t.Fatalf("cross-version check: code=%d out=%q err=%s", code, out, errout)
	}
}

// A layout with only local fragments (no imports) writes a marker and a lock with
// no source tables.
func TestRenderFragmentsNone(t *testing.T) {
	repo(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"intro\"]\n")
	write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "# Repo\n\nOnly local prose.\n")
	if code, _, errout := exec("render"); code != 0 {
		t.Fatalf("render exit = %d: %s", code, errout)
	}
	disk, _ := os.ReadFile("AGENTS.md")
	if firstLine(string(disk)) != mdMarker(".claude/fragments/AGENTS.md") {
		t.Fatalf("marker missing: %q", firstLine(string(disk)))
	}
	lock, _ := os.ReadFile(".claude/fragments/cc-guides.lock")
	if strings.Contains(string(lock), "[sources.") {
		t.Fatalf("import-free layout must lock no sources:\n%s", lock)
	}
	if code, out, _ := exec("check"); code != 0 || out != "OK\tAGENTS.md\n" {
		t.Fatalf("check: code=%d out=%q", code, out)
	}
}

func TestRenderShellArtifactWithArgs(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/plugin/scripts/install.sh/layout.toml",
		"fragments = [ { use = \"cc-skills:install\", args = { binary = \"slop-cop\" } } ]\n"+ccSkillsSource)

	if code, _, errout := exec("render", "--source", srcFlag(fixture)); code != 0 {
		t.Fatalf("render exit = %d: %s", code, errout)
	}
	disk, err := os.ReadFile("plugin/scripts/install.sh")
	if err != nil {
		t.Fatal(err)
	}
	lines := strings.Split(string(disk), "\n")
	if lines[0] != "#!/bin/sh" {
		t.Fatalf("line 1 = %q, want shebang", lines[0])
	}
	if lines[1] != shMarker(".claude/fragments/plugin/scripts/install.sh") {
		t.Fatalf("line 2 = %q, want marker", lines[1])
	}
	if !strings.Contains(string(disk), `NAME="slop-cop"`) {
		t.Fatalf("substitution missing:\n%s", disk)
	}
	info, _ := os.Stat("plugin/scripts/install.sh")
	if info.Mode().Perm()&0o111 == 0 {
		t.Errorf("new .sh artifact must be executable, mode=%v", info.Mode().Perm())
	}
	if code, out, errout := exec("check", "--source", srcFlag(fixture)); code != 0 {
		t.Fatalf("check exit=%d out=%q err=%s", code, out, errout)
	}
}

func TestDiscoveryGuardStrayFile(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"intro\"]\n")
	write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "# I\n")
	write(t, ".claude/fragments/AGENTS.md/stray.txt", "junk\n")
	code, _, errout := exec("render", "--source", srcFlag(fixture))
	if code != 2 || !strings.Contains(errout, "stray file") {
		t.Fatalf("code=%d err=%q, want stray file error", code, errout)
	}
}

func TestDiscoveryGuardUnreferencedFragment(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"intro\"]\n")
	write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "# I\n")
	write(t, ".claude/fragments/AGENTS.md/orphan.fragment.md", "dropped\n")
	code, _, errout := exec("render", "--source", srcFlag(fixture))
	if code != 2 || !strings.Contains(errout, "not referenced") {
		t.Fatalf("code=%d err=%q, want unreferenced error", code, errout)
	}
}

func TestDiscoveryGuardMissingLocalFragment(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"intro\"]\n")
	code, _, errout := exec("render", "--source", srcFlag(fixture))
	if code != 2 || !strings.Contains(errout, "do not exist") {
		t.Fatalf("code=%d err=%q, want missing-file error", code, errout)
	}
}

func TestDiscoveryGuardNestedSubdir(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)
	write(t, ".claude/fragments/AGENTS.md/nested/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)
	code, _, errout := exec("render", "--source", srcFlag(fixture))
	if code != 2 || !strings.Contains(errout, "flat") {
		t.Fatalf("code=%d err=%q, want flatness error", code, errout)
	}
}

func TestHandwrittenOverwriteRefused(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)
	write(t, "AGENTS.md", "handwritten, no marker\n")
	code, _, errout := exec("render", "--source", srcFlag(fixture))
	if code != 2 || !strings.Contains(errout, "handwritten") {
		t.Fatalf("code=%d err=%q", code, errout)
	}
	if code, _, _ := exec("render", "--source", srcFlag(fixture), "--force"); code != 0 {
		t.Fatalf("--force exit = %d", code)
	}
}

// A legacy pre-lock banner no longer marks a file as managed: render refuses it
// like any handwritten file. Adopt via --force once; the lock then owns the
// target, so a plain re-render succeeds.
func TestRenderLegacyBannerNoLongerOverwritable(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)
	write(t, "AGENTS.md", "<!-- cc-guides 0.1.7 src=.claude/fragments/AGENTS.md fragments=local | GENERATED — do not edit -->\n## Compact Context\nccx body\n")
	code, _, errout := exec("render", "--source", srcFlag(fixture))
	if code != 2 || !strings.Contains(errout, "handwritten") {
		t.Fatalf("code=%d err=%q, want handwritten-overwrite refusal", code, errout)
	}
	if code, _, errout := exec("render", "--source", srcFlag(fixture), "--force"); code != 0 {
		t.Fatalf("--force adoption: code=%d err=%s", code, errout)
	}
	if code, _, errout := exec("render", "--source", srcFlag(fixture)); code != 0 {
		t.Fatalf("re-render after adoption: code=%d err=%s", code, errout)
	}
}

func TestLint(t *testing.T) {
	dir := t.TempDir()
	write(t, filepath.Join(dir, "md", "ok.md"), "## Clean\nbody\n")
	write(t, filepath.Join(dir, "sh", "ok.sh"), "#!/bin/sh\necho hi\n")
	if code, _, _ := exec("lint", dir); code != 0 {
		t.Fatalf("clean lint exit = %d", code)
	}
	// A CRLF fragment reddens the gate.
	write(t, filepath.Join(dir, "md", "bad.md"), "line\r\nbody\n")
	code, _, errout := exec("lint", dir)
	if code != 1 || !strings.Contains(errout, "CRLF") {
		t.Fatalf("dirty lint: code=%d err=%q", code, errout)
	}
}

func TestLintShellMustHaveShebang(t *testing.T) {
	dir := t.TempDir()
	write(t, filepath.Join(dir, "sh", "noshebang.sh"), "echo hi\n")
	code, _, errout := exec("lint", dir)
	if code != 1 || !strings.Contains(errout, "shebang") {
		t.Fatalf("code=%d err=%q", code, errout)
	}
}

// A README.md at the pack root is documentation, not a fragment: it must not
// redden the gate even sitting next to real fragments.
func TestLintPackRootReadme(t *testing.T) {
	dir := t.TempDir()
	write(t, filepath.Join(dir, "README.md"), "# The Pack\n\nHumans read this.\n")
	write(t, filepath.Join(dir, "md", "ok.md"), "## Clean\nbody\n")
	write(t, filepath.Join(dir, "sh", "ok.sh"), "#!/bin/sh\necho hi\n")
	if code, _, errout := exec("lint", dir); code != 0 {
		t.Fatalf("pack-root README lint: code=%d err=%s", code, errout)
	}
}

// A README.md below the pack root (e.g. under md/) is rejected so it can never
// be resolved as the fragment named "README".
func TestLintReadmeUnderKindDirRejected(t *testing.T) {
	dir := t.TempDir()
	write(t, filepath.Join(dir, "md", "README.md"), "## Not\nbody\n")
	code, _, errout := exec("lint", dir)
	if code != 1 || !strings.Contains(errout, "reserved documentation") {
		t.Fatalf("md/README.md lint: code=%d err=%q", code, errout)
	}
}

func TestCatImportAndLocal(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	code, out, _ := exec("cat", "--source", srcFlag(fixture), "cc-skills:ccx")
	if code != 0 || !strings.HasPrefix(out, "## Compact Context") {
		t.Fatalf("cat import: code=%d out=%q", code, firstLine(out))
	}
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"intro\"]\n")
	write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "# Local Intro\nbody\n")
	code, out, _ = exec("cat", "intro")
	if code != 0 || !strings.HasPrefix(out, "# Local Intro") {
		t.Fatalf("cat local: code=%d out=%q", code, firstLine(out))
	}
	if code, _, _ := exec("cat", "--source", srcFlag(fixture), "cc-skills:nonesuch"); code != 2 {
		t.Fatalf("unknown import exit = %d, want 2", code)
	}
}

func TestList(t *testing.T) {
	repo(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"intro\", \"cc-skills:ccx\"]\n"+ccSkillsSource)
	write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "# I\n")
	code, out, _ := exec("list")
	if code != 0 {
		t.Fatalf("list exit = %d", code)
	}
	if !strings.Contains(out, "AGENTS.md\tmd\tintro,cc-skills:ccx") {
		t.Fatalf("list out = %q", out)
	}
}

func TestNoUnitsNotice(t *testing.T) {
	repo(t)
	code, out, errout := exec("render")
	if code != 0 || out != "" || !strings.Contains(errout, "no artifact dirs") {
		t.Fatalf("code=%d out=%q err=%q", code, out, errout)
	}
}

func TestUnknownCommandExit2(t *testing.T) {
	repo(t)
	if code, _, _ := exec("frobnicate"); code != 2 {
		t.Fatalf("exit = %d, want 2", code)
	}
}

// #2: a LOCAL entry declaring args must be token-substituted with two-way strictness.
func TestRenderLocalFragmentArgs(t *testing.T) {
	repo(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [ { use = \"intro\", args = { name = \"repo\" } } ]\n")
	write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "Hello {{name}}.\n")
	if code, _, errout := exec("render"); code != 0 {
		t.Fatalf("render exit = %d: %s", code, errout)
	}
	disk, _ := os.ReadFile("AGENTS.md")
	if !strings.Contains(string(disk), "Hello repo.") || strings.Contains(string(disk), "{{name}}") {
		t.Fatalf("local args not substituted:\n%s", disk)
	}
}

func TestRenderLocalFragmentArgsStrict(t *testing.T) {
	repo(t)
	// An arg the local fragment never consumes must hard-error (two-way strictness).
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [ { use = \"intro\", args = { unused = \"x\" } } ]\n")
	write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "no tokens here\n")
	if code, _, errout := exec("render"); code != 2 || !strings.Contains(errout, "no matching {{token}}") {
		t.Fatalf("code=%d err=%q, want unused-arg error", code, errout)
	}
}

// #1: a whitespace-only local fragment is rejected, not rendered as stray blanks.
func TestRenderWhitespaceOnlyLocalFragmentRejected(t *testing.T) {
	repo(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"intro\", \"body\"]\n")
	write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "# Head\n")
	write(t, ".claude/fragments/AGENTS.md/body.fragment.md", " \n \n")
	if code, _, errout := exec("render"); code != 2 || !strings.Contains(errout, "whitespace-only") {
		t.Fatalf("code=%d err=%q, want whitespace-only error", code, errout)
	}
}

// A json layout dir deep-merges local json fragments, writes a marker-free
// artifact, registers it in the lock, and round-trips through check.
func TestRenderCheckJSON(t *testing.T) {
	repo(t)
	write(t, ".claude/fragments/.claude/settings.json/layout.toml", "fragments = [\"base\", \"extra\"]\n")
	write(t, ".claude/fragments/.claude/settings.json/base.fragment.json", "{\n  \"permissions\": {\n    \"allow\": [\"Read\"]\n  }\n}\n")
	write(t, ".claude/fragments/.claude/settings.json/extra.fragment.json", "{\n  \"permissions\": {\n    \"allow\": [\"Bash(go:*)\"]\n  },\n  \"model\": \"opus\"\n}\n")

	if code, _, errout := exec("render"); code != 0 {
		t.Fatalf("json render exit=%d: %s", code, errout)
	}
	disk, err := os.ReadFile(".claude/settings.json")
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(disk), "GENERATED") {
		t.Fatalf("json artifact must carry no marker:\n%s", disk)
	}
	want := "{\n  \"permissions\": {\n    \"allow\": [\n      \"Read\",\n      \"Bash(go:*)\"\n    ]\n  },\n  \"model\": \"opus\"\n}\n"
	if string(disk) != want {
		t.Fatalf("merged json:\n%s\nwant:\n%s", disk, want)
	}
	lock, _ := os.ReadFile(".claude/fragments/cc-guides.lock")
	if !strings.Contains(string(lock), ".claude/settings.json") {
		t.Fatalf("lock must register the json artifact:\n%s", lock)
	}
	if code, out, errout := exec("check"); code != 0 || out != "OK\t.claude/settings.json\n" {
		t.Fatalf("json check: code=%d out=%q err=%s", code, out, errout)
	}
	// A byte change to the artifact is STALE.
	write(t, ".claude/settings.json", "{\n  \"model\": \"different\"\n}\n")
	if code, out, _ := exec("check"); code != 1 || out != "STALE\t.claude/settings.json\n" {
		t.Fatalf("json tamper: code=%d out=%q", code, out)
	}
}

// json has no marker, so the lock's artifact registry is the only clobber-safety
// mechanism: a handwritten target is refused, --force adopts it into the lock, and
// subsequent renders are then allowed.
func TestJSONHandwrittenClobberGuard(t *testing.T) {
	repo(t)
	write(t, ".claude/fragments/.claude/settings.json/layout.toml", "fragments = [\"base\"]\n")
	write(t, ".claude/fragments/.claude/settings.json/base.fragment.json", "{\n  \"model\": \"opus\"\n}\n")
	write(t, ".claude/settings.json", "{ \"handwritten\": true }\n")

	if code, _, errout := exec("render"); code != 2 || !strings.Contains(errout, "handwritten") {
		t.Fatalf("json clobber guard: code=%d err=%q", code, errout)
	}
	if code, _, errout := exec("render", "--force"); code != 0 {
		t.Fatalf("force render: code=%d err=%s", code, errout)
	}
	if code, _, errout := exec("render"); code != 0 {
		t.Fatalf("re-render after lock adopts the target: code=%d err=%s", code, errout)
	}
}

func TestLintJSON(t *testing.T) {
	dir := t.TempDir()
	write(t, filepath.Join(dir, "json", "ok.json"), "{\n  \"a\": 1\n}\n")
	// {{token}} placeholders are tolerated, in a string or a value position.
	write(t, filepath.Join(dir, "json", "strtoken.json"), "{\n  \"p\": \"{{venv}}/x\"\n}\n")
	write(t, filepath.Join(dir, "json", "valtoken.json"), "{\n  \"count\": {{n}}\n}\n")
	if code, _, errout := exec("lint", dir); code != 0 {
		t.Fatalf("clean json lint: code=%d err=%s", code, errout)
	}
	// A non-object root reddens the gate.
	write(t, filepath.Join(dir, "json", "bad.json"), "[1, 2]\n")
	if code, _, errout := exec("lint", dir); code != 1 || !strings.Contains(errout, "object") {
		t.Fatalf("bad json lint: code=%d err=%q", code, errout)
	}
}

// A marker'd artifact with no lock entry cannot be pinned — invalid input.
func TestCheckMarkerNoLockInvalid(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)
	write(t, "AGENTS.md", mdMarker(".claude/fragments/AGENTS.md")+"\n## Compact Context\nccx body\n")
	if code, _, errout := exec("check", "--source", srcFlag(fixture)); code != 2 || !strings.Contains(errout, "no cc-guides.lock") {
		t.Fatalf("marker-no-lock: code=%d err=%q", code, errout)
	}
}

// A partial lock routes per artifact: the locked target still checks OK, while a
// sibling absent from the (non-nil) lock is invalid input — there is no banner
// fallback anymore, so the repo must render to register it.
func TestCheckPartialLockPerArtifact(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)
	if code, _, errout := exec("render", "--source", srcFlag(fixture)); code != 0 {
		t.Fatalf("render: code=%d err=%s", code, errout)
	}
	// A sibling layout whose artifact carries a marker but has no lock entry.
	write(t, ".claude/fragments/CLAUDE.md/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)
	write(t, "CLAUDE.md", mdMarker(".claude/fragments/CLAUDE.md")+"\n## Compact Context\nccx body\n")

	code, out, errout := exec("check", "--source", srcFlag(fixture))
	if code != 2 {
		t.Fatalf("partial-lock check: code=%d out=%q err=%s, want 2", code, out, errout)
	}
	if !strings.Contains(out, "OK\tAGENTS.md") {
		t.Fatalf("locked artifact must still check OK, got %q", out)
	}
	if !strings.Contains(errout, "no cc-guides.lock entry") || !strings.Contains(errout, "CLAUDE.md") {
		t.Fatalf("unlocked sibling must be invalid input naming CLAUDE.md, got %q", errout)
	}
}

// The lock detects a spec that no longer matches the layout and demands a re-render.
func TestCheckStaleLock(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)
	if code, _, errout := exec("render", "--source", srcFlag(fixture)); code != 0 {
		t.Fatalf("render: code=%d err=%s", code, errout)
	}
	// Re-check WITHOUT the --source override: the effective spec (the manifest form
	// in the layout) no longer matches the lock's recorded local override spec.
	if code, _, errout := exec("check"); code != 2 || !strings.Contains(errout, "lock out of date") {
		t.Fatalf("stale lock: code=%d err=%q", code, errout)
	}
}

// A full render is authoritative: removing a layout dir and re-rendering rebuilds
// the lock so the removed target is pruned, which restores clobber-safety at that
// path (a later layout there cannot overwrite the leftover file without --force).
func TestFullRenderRebuildsLockPruningRemovedTarget(t *testing.T) {
	repo(t)
	write(t, ".claude/fragments/.claude/settings.json/layout.toml", "fragments = [\"base\"]\n")
	write(t, ".claude/fragments/.claude/settings.json/base.fragment.json", "{\n  \"model\": \"opus\"\n}\n")
	write(t, ".claude/fragments/extra.json/layout.toml", "fragments = [\"base\"]\n")
	write(t, ".claude/fragments/extra.json/base.fragment.json", "{\n  \"n\": 1\n}\n")
	if code, _, errout := exec("render"); code != 0 {
		t.Fatalf("render: code=%d err=%s", code, errout)
	}
	lock, _ := os.ReadFile(".claude/fragments/cc-guides.lock")
	if !strings.Contains(string(lock), "extra.json") {
		t.Fatalf("lock must register both targets:\n%s", lock)
	}
	// Remove the extra.json layout dir; its rendered artifact stays on disk.
	if err := os.RemoveAll(".claude/fragments/extra.json"); err != nil {
		t.Fatal(err)
	}
	if code, _, errout := exec("render"); code != 0 {
		t.Fatalf("re-render: code=%d err=%s", code, errout)
	}
	lock2, _ := os.ReadFile(".claude/fragments/cc-guides.lock")
	if strings.Contains(string(lock2), "extra.json") {
		t.Fatalf("full render must prune the removed target from the lock:\n%s", lock2)
	}
	// The pruned target is no longer lock-registered, so a new layout at that path
	// cannot clobber the leftover json without --force.
	write(t, ".claude/fragments/extra.json/layout.toml", "fragments = [\"base\"]\n")
	write(t, ".claude/fragments/extra.json/base.fragment.json", "{\n  \"n\": 2\n}\n")
	if code, _, errout := exec("render"); code != 2 || !strings.Contains(errout, "handwritten") {
		t.Fatalf("clobber-safety must be restored after prune: code=%d err=%q", code, errout)
	}
}

// An unreadable target (here a directory in the artifact's place) is a hard error
// in the preflight, never treated as absent — otherwise the lock would register it
// and a later retry would clobber it without --force.
func TestRenderUnreadableTargetErrorsBeforeLock(t *testing.T) {
	repo(t)
	write(t, ".claude/fragments/.claude/settings.json/layout.toml", "fragments = [\"base\"]\n")
	write(t, ".claude/fragments/.claude/settings.json/base.fragment.json", "{\n  \"model\": \"opus\"\n}\n")
	if err := os.MkdirAll(".claude/settings.json", 0o750); err != nil {
		t.Fatal(err)
	}
	if code, _, errout := exec("render"); code != 2 {
		t.Fatalf("unreadable target must be a hard error: code=%d err=%s", code, errout)
	}
	if _, err := os.Stat(".claude/fragments/cc-guides.lock"); !os.IsNotExist(err) {
		t.Fatal("a preflight failure must not write the lock (which would register the target)")
	}
}

// A path-scoped render is surgical: it merges into the lock, preserving artifacts
// it did not render (unlike a full render, which rebuilds and would drop them).
func TestScopedRenderMergesLock(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)
	write(t, ".claude/fragments/CLAUDE.md/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)
	if code, _, errout := exec("render", "--source", srcFlag(fixture)); code != 0 {
		t.Fatalf("full render: code=%d err=%s", code, errout)
	}
	lock, _ := os.ReadFile(".claude/fragments/cc-guides.lock")
	if !strings.Contains(string(lock), `"AGENTS.md"`) || !strings.Contains(string(lock), `"CLAUDE.md"`) {
		t.Fatalf("full render must register both:\n%s", lock)
	}
	if code, _, errout := exec("render", ".claude/fragments/AGENTS.md", "--source", srcFlag(fixture)); code != 0 {
		t.Fatalf("scoped render: code=%d err=%s", code, errout)
	}
	lock2, _ := os.ReadFile(".claude/fragments/cc-guides.lock")
	if !strings.Contains(string(lock2), `"CLAUDE.md"`) {
		t.Fatalf("scoped render must preserve the untouched artifact in the lock:\n%s", lock2)
	}
}

// A scoped render whose layout spec no longer matches the lock's recorded spec for
// a shared alias cannot pin safely — it must demand a full render.
func TestScopedRenderSpecDisagreementErrors(t *testing.T) {
	repo(t)
	fixture := guidesFixture(t)
	other := guidesFixture(t)
	write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"cc-skills:ccx\"]\n"+ccSkillsSource)
	if code, _, errout := exec("render", "--source", srcFlag(fixture)); code != 0 {
		t.Fatalf("render: code=%d err=%s", code, errout)
	}
	code, _, errout := exec("render", ".claude/fragments/AGENTS.md", "--source", "cc-skills="+other)
	if code != 2 || !strings.Contains(errout, "full") {
		t.Fatalf("spec disagreement must demand a full render: code=%d err=%q", code, errout)
	}
}

func firstLine(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}
