package cli_test

import (
	"context"
	osexec "os/exec"
	"strings"
	"testing"

	"github.com/yasyf/cc-guides/lockfile"
)

// prCheckBaseLock is a minimal valid lock recording one artifact and no sources.
const prCheckBaseLock = "# Written by 'cc-guides render' — do not edit.\n" +
	"schema = 1\nversion = \"0.1.0\"\nartifacts = [\"AGENTS.md\"]\n"

// runGitT runs git in dir, failing the test on error. pr-check shells out to git,
// so its tests need real history (the shared repo() helper only makes a .git dir).
func runGitT(t *testing.T, dir string, args ...string) string {
	t.Helper()
	c := osexec.CommandContext(context.Background(), "git", args...) // #nosec G204 -- fixed "git" command, args are test constants
	c.Dir = dir
	out, err := c.CombinedOutput()
	if err != nil {
		t.Fatalf("git %v: %v\n%s", args, err, out)
	}
	return strings.TrimSpace(string(out))
}

// gitRepo initializes a real git repo and chdirs into it.
func gitRepo(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	t.Chdir(dir)
	runGitT(t, dir, "init", "-q", "-b", "main")
	runGitT(t, dir, "config", "user.email", "t@t")
	runGitT(t, dir, "config", "user.name", "t")
	return dir
}

func TestPRCheck(t *testing.T) {
	tests := []struct {
		name       string
		withLock   bool
		change     func(t *testing.T)
		wantCode   int
		wantStdout string
	}{
		{
			name:       "no lock owns nothing",
			withLock:   false,
			change:     func(t *testing.T) { write(t, "AGENTS.md", "hand edit\n") },
			wantCode:   0,
			wantStdout: "cc-guides: no lock — nothing is CI-owned\n",
		},
		{
			name:       "editing a fragment is allowed",
			withLock:   true,
			change:     func(t *testing.T) { write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "# edited\n") },
			wantCode:   0,
			wantStdout: "cc-guides: no CI-owned artifact was hand-edited\n",
		},
		{
			name:       "editing a rendered artifact is a violation",
			withLock:   true,
			change:     func(t *testing.T) { write(t, "AGENTS.md", "tampered\n") },
			wantCode:   1,
			wantStdout: "AGENTS.md is CI-owned (rendered by cc-guides) — edit .claude/fragments/AGENTS.md/ instead\n",
		},
		{
			name:     "editing the lock is a violation",
			withLock: true,
			change: func(t *testing.T) {
				write(t, lockfile.Path, strings.Replace(prCheckBaseLock, `version = "0.1.0"`, `version = "9.9.9"`, 1))
			},
			wantCode:   1,
			wantStdout: ".claude/fragments/cc-guides.lock is CI-owned (regenerated by cc-guides) — do not edit it directly\n",
		},
		{
			name:     "an unowned file alongside an artifact edit is not flagged",
			withLock: true,
			change: func(t *testing.T) {
				write(t, "AGENTS.md", "tampered\n")
				write(t, "README.md", "# readme\n")
			},
			wantCode:   1,
			wantStdout: "AGENTS.md is CI-owned (rendered by cc-guides) — edit .claude/fragments/AGENTS.md/ instead\n",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := gitRepo(t)
			write(t, ".claude/fragments/AGENTS.md/layout.toml", "fragments = [\"intro\"]\n")
			write(t, ".claude/fragments/AGENTS.md/intro.fragment.md", "# Repo\n")
			write(t, "AGENTS.md", "# Repo\n")
			if tt.withLock {
				write(t, lockfile.Path, prCheckBaseLock)
			}
			runGitT(t, dir, "add", "-A")
			runGitT(t, dir, "commit", "-q", "-m", "base")
			base := runGitT(t, dir, "rev-parse", "HEAD")

			tt.change(t)
			runGitT(t, dir, "add", "-A")
			runGitT(t, dir, "commit", "-q", "-m", "pr")

			code, stdout, stderr := exec("pr-check", base)
			if code != tt.wantCode || stdout != tt.wantStdout {
				t.Fatalf("pr-check: code=%d stdout=%q stderr=%q; want code=%d stdout=%q", code, stdout, stderr, tt.wantCode, tt.wantStdout)
			}
		})
	}
}

// A bad base ref is invalid input (exit 2), not a false all-clear.
func TestPRCheckBadBase(t *testing.T) {
	dir := gitRepo(t)
	write(t, lockfile.Path, prCheckBaseLock)
	write(t, "AGENTS.md", "# Repo\n")
	runGitT(t, dir, "add", "-A")
	runGitT(t, dir, "commit", "-q", "-m", "base")

	if code, _, _ := exec("pr-check", "nonexistent-ref"); code != 2 {
		t.Fatalf("bad base: code=%d, want 2", code)
	}
}
