package cli

import (
	"context"
	"fmt"
	"path"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/yasyf/cc-guides/guide"
	"github.com/yasyf/cc-guides/lockfile"
)

func newPRCheckCmd(ctx context.Context) *cobra.Command {
	return &cobra.Command{
		Use:   "pr-check <base>",
		Short: "Fail a PR that hand-edits a CI-owned rendered artifact",
		Long: "Compare the PR's changed files (git diff --name-only <base>...HEAD)\n" +
			"against the cc-guides-owned set — every artifact the lock records plus the\n" +
			"lock file itself — and exit 1 with one line per violation if any owned file\n" +
			"was edited directly. A repo with no lock owns nothing and passes. Intended\n" +
			"for the pull_request job.",
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runPRCheck(ctx, cmd, args[0])
		},
	}
}

func runPRCheck(ctx context.Context, cmd *cobra.Command, base string) error {
	out := cmd.OutOrStdout()
	root := repoRoot()

	lock, present, err := lockfile.Load(root)
	if err != nil {
		return exit(2, err)
	}
	if !present {
		foutln(out, "cc-guides: no lock — nothing is CI-owned")
		return nil
	}

	owned, err := ownedViolations(root, lock)
	if err != nil {
		return exit(2, err)
	}
	changed, err := gitCapture(ctx, root, "diff", "--name-only", base+"...HEAD")
	if err != nil {
		return exit(2, err)
	}

	var violations []string
	for _, f := range strings.Split(changed, "\n") {
		if msg, ok := owned[strings.TrimSpace(f)]; ok {
			violations = append(violations, msg)
		}
	}
	if len(violations) == 0 {
		foutln(out, "cc-guides: no CI-owned artifact was hand-edited")
		return nil
	}
	sort.Strings(violations)
	for _, v := range violations {
		foutln(out, v)
	}
	return silent(1)
}

// ownedViolations maps every cc-guides-owned repo path to the message printed when
// a PR edits it directly: each rendered artifact the lock records (edit its
// fragment dir instead), plus the lock file itself (CI regenerates it). The dirs
// are re-derived from the tree rather than read from the lock, which records
// targets alone: under a `target` override the dir no longer mirrors the target.
//
// That derivation is best-effort by design. pr-check decides whether a PR touched a
// file it must not, which the lock alone answers; the dirs only improve the message
// that names where to edit instead. So a dir that fails to load contributes no entry
// rather than failing the command — one broken dir anywhere in the repo must not
// block every unrelated PR across the fleet. A target left without an entry, whether
// its dir is gone or unreadable, names the path an override-free layout would
// occupy. Two dirs claiming one target is the exception: that is a repo-wide
// misconfiguration render and check both refuse, so pr-check refuses it too rather
// than silently picking a winner.
func ownedViolations(root string, lock *lockfile.Lock) (map[string]string, error) {
	dirs, err := collectDirs(root, nil)
	if err != nil {
		return nil, err
	}
	loaded := make([]*artifactDir, 0, len(dirs))
	for _, dir := range dirs {
		ad, err := loadArtifactDir(root, dir)
		if err != nil {
			continue
		}
		loaded = append(loaded, ad)
	}
	if err := conflictingTargets(loaded); err != nil {
		return nil, err
	}
	byTarget := make(map[string]string, len(loaded))
	for _, ad := range loaded {
		byTarget[ad.target] = ad.dir
	}

	owned := make(map[string]string, len(lock.Artifacts)+1)
	for _, target := range lock.Artifacts {
		dir, ok := byTarget[target]
		if !ok {
			dir = path.Join(guide.FragmentsRoot, target)
		}
		owned[target] = fmt.Sprintf("%s is CI-owned (rendered by cc-guides) — edit %s/ instead", target, dir)
	}
	owned[lockfile.Path] = fmt.Sprintf("%s is CI-owned (regenerated by cc-guides) — do not edit it directly", lockfile.Path)
	return owned, nil
}
