package cli

import (
	"context"
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/yasyf/cc-guides/guide"
	"github.com/yasyf/cc-guides/lockfile"
)

func newPRCheckCmd(ctx context.Context) *cobra.Command {
	return &cobra.Command{
		Use:   "pr-check <base>",
		Short: "Fail a PR that hand-edits a CI-owned rendered artifact",
		Long: "Compare the PR's changed files (git diff --name-only <base>...HEAD)\n" +
			"against the cc-guides-owned set — every artifact the lock records plus the\n" +
			"lock file itself — and exit 1 with one line per violation if any owned file\n" +
			"was edited directly. A repo with no lock owns nothing and passes. Intended\n" +
			"for the pull_request job.",
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runPRCheck(ctx, cmd, args[0])
		},
	}
}

func runPRCheck(ctx context.Context, cmd *cobra.Command, base string) error {
	out := cmd.OutOrStdout()
	root := repoRoot()

	lock, present, err := lockfile.Load(root)
	if err != nil {
		return exit(2, err)
	}
	if !present {
		foutln(out, "cc-guides: no lock — nothing is CI-owned")
		return nil
	}

	owned := ownedViolations(lock)
	changed, err := gitCapture(ctx, root, "diff", "--name-only", base+"...HEAD")
	if err != nil {
		return exit(2, err)
	}

	var violations []string
	for _, f := range strings.Split(changed, "\n") {
		if msg, ok := owned[strings.TrimSpace(f)]; ok {
			violations = append(violations, msg)
		}
	}
	if len(violations) == 0 {
		foutln(out, "cc-guides: no CI-owned artifact was hand-edited")
		return nil
	}
	sort.Strings(violations)
	for _, v := range violations {
		foutln(out, v)
	}
	return silent(1)
}

// ownedViolations maps every cc-guides-owned repo path to the message printed when
// a PR edits it directly: each rendered artifact the lock records (edit its
// fragment dir instead), plus the lock file itself (CI regenerates it).
func ownedViolations(lock *lockfile.Lock) map[string]string {
	owned := make(map[string]string, len(lock.Artifacts)+1)
	for _, target := range lock.Artifacts {
		owned[target] = fmt.Sprintf("%s is CI-owned (rendered by cc-guides) — edit %s/%s/ instead", target, guide.FragmentsRoot, target)
	}
	owned[lockfile.Path] = fmt.Sprintf("%s is CI-owned (regenerated by cc-guides) — do not edit it directly", lockfile.Path)
	return owned
}
