package guide_test

import (
	"strings"
	"testing"

	"github.com/yasyf/cc-guides/guide"
)

// The gitignore marker is the shell `# ` comment form, exact — same syntax as sh/yml/toml.
func TestGitignoreMarkerExact(t *testing.T) {
	got := guide.MarkerLine(guide.KindGitignore, "x")
	want := "# GENERATED by cc-guides from x/ — do not edit; edit the fragments and run 'cc-guides render'."
	if got != want {
		t.Fatalf("gitignore marker = %q, want %q", got, want)
	}
}

// AddMarker / ParseMarker / StripMarker round-trip on a gitignore body: no shebang
// branch, so the marker is line 1 and strips cleanly, and the src round-trips.
func TestGitignoreMarkerAddParseStripRoundTrip(t *testing.T) {
	cases := []struct {
		src  string
		body string
	}{
		{".claude/fragments/.gitignore", "node_modules/\n*.log\n"},
		{".claude/fragments/docs/.gitignore", "# a load-bearing comment\n_site/\n"},
	}
	for _, tc := range cases {
		final := guide.AddMarker(guide.KindGitignore, tc.src, []byte(tc.body))
		if !strings.HasSuffix(string(final), "\n") || strings.HasSuffix(string(final), "\n\n") {
			t.Errorf("marker output must end in exactly one newline: %q", final)
		}
		if !strings.HasPrefix(string(final), guide.MarkerLine(guide.KindGitignore, tc.src)+"\n") {
			t.Fatalf("gitignore marker must lead line 1: %q", final)
		}
		info, ok := guide.ParseMarker(guide.KindGitignore, final)
		if !ok || info.Src != tc.src {
			t.Fatalf("ParseMarker = %+v ok=%v, want src=%q", info, ok, tc.src)
		}
		got, ok := guide.StripMarker(guide.KindGitignore, final)
		if !ok || string(got) != tc.body {
			t.Fatalf("StripMarker round-trip:\n got %q\nwant %q", got, tc.body)
		}
	}
}

// A gitignore artifact concatenates its pattern fragments like yaml/toml (one blank
// line between pieces, never a semantic merge), so comments survive verbatim.
func TestComposeGitignore(t *testing.T) {
	pieces := []guide.Piece{
		{Body: []byte("# build output\nnode_modules/\n"), Origin: "base.gitignore"},
		{Body: []byte("*.log\n"), Origin: "logs.gitignore"},
	}
	got, err := guide.Compose(guide.KindGitignore, pieces)
	if err != nil {
		t.Fatal(err)
	}
	want := "# build output\nnode_modules/\n\n*.log\n"
	if string(got) != want {
		t.Fatalf("gitignore compose =\n%q\nwant\n%q", got, want)
	}
}

// gitignore has no textual, syntax, or semantic validator, so any pure body lints
// clean — a `{{token}}`-bearing pattern included (tokens are substituted at compose).
func TestGitignoreLintTokens(t *testing.T) {
	if vs := guide.KindGitignore.Lint([]byte("{{dir}}/\n*.tmp\n")); len(vs) != 0 {
		t.Fatalf("a token-bearing gitignore fragment must lint clean, got %v", vs)
	}
}

// gitignore has no semantic validator, so post-compose validation is a no-op — it
// accepts any composed body (parallel to md).
func TestGitignorePostComposeNoop(t *testing.T) {
	if err := guide.KindGitignore.PostComposeValidate([]byte("anything at all\n")); err != nil {
		t.Fatalf("gitignore must be exempt from post-compose validation, got %v", err)
	}
}
