package guide_test

import (
	"strings"
	"testing"

	"github.com/yasyf/cc-guides/guide"
)

// The marker core regex is the stable machine contract; pin it verbatim.
const pinnedMarkerCoreRegex = `GENERATED by cc-guides from (?P<src>\S+)/ — do not edit; edit the fragments and (?:push — CI renders|run 'cc-guides render')\.`

func TestMarkerCoreRegexPinned(t *testing.T) {
	if guide.MarkerCoreRegex != pinnedMarkerCoreRegex {
		t.Fatalf("MarkerCoreRegex drifted:\n got: %s\nwant: %s", guide.MarkerCoreRegex, pinnedMarkerCoreRegex)
	}
}

func TestMarkerCoreExact(t *testing.T) {
	got := guide.MarkerLine(guide.KindMD, ".claude/fragments/AGENTS.md")
	want := "<!-- GENERATED by cc-guides from .claude/fragments/AGENTS.md/ — do not edit; edit the fragments and push — CI renders. -->"
	if got != want {
		t.Fatalf("md marker = %q\nwant %q", got, want)
	}
	if sh := guide.MarkerLine(guide.KindSH, "x"); sh != "# GENERATED by cc-guides from x/ — do not edit; edit the fragments and push — CI renders." {
		t.Fatalf("sh marker = %q", sh)
	}
	// yaml shares the shell `# ` comment marker.
	if yml := guide.MarkerLine(guide.KindYAML, "x"); yml != "# GENERATED by cc-guides from x/ — do not edit; edit the fragments and push — CI renders." {
		t.Fatalf("yml marker = %q", yml)
	}
}

// The pre-CI-render marker core (run 'cc-guides render') must still parse as
// generated so render overwrites a fleet artifact still carrying it, rather than
// refusing it as handwritten.
func TestParseMarkerAcceptsLegacyCore(t *testing.T) {
	const legacyMD = "<!-- GENERATED by cc-guides from .claude/fragments/AGENTS.md/ — do not edit; edit the fragments and run 'cc-guides render'. -->"
	info, ok := guide.ParseMarker(guide.KindMD, []byte(legacyMD+"\nbody\n"))
	if !ok || info.Src != ".claude/fragments/AGENTS.md" {
		t.Fatalf("legacy md marker: ParseMarker = %+v ok=%v, want src=.claude/fragments/AGENTS.md", info, ok)
	}
	const legacySH = "# GENERATED by cc-guides from s.sh/ — do not edit; edit the fragments and run 'cc-guides render'."
	if _, ok := guide.ParseMarker(guide.KindSH, []byte("#!/bin/sh\n"+legacySH+"\nset -e\n")); !ok {
		t.Fatal("legacy sh marker after a shebang must parse as generated")
	}
}

// AddMarker / ParseMarker / StripMarker round-trip, including the shell
// shebang-preserving case, and the src round-trips.
func TestMarkerAddParseStripRoundTrip(t *testing.T) {
	cases := []struct {
		kind guide.Kind
		src  string
		body string
	}{
		{guide.KindMD, ".claude/fragments/AGENTS.md", "# head\n\nbody\n"},
		{guide.KindSH, ".claude/fragments/plugin/scripts/install.sh", "echo hi\n"},
		{guide.KindSH, ".claude/fragments/plugin/scripts/install.sh", "#!/bin/sh\nset -e\necho hi\n"},
		{guide.KindYAML, ".claude/fragments/.github/workflows/docs.yml", "name: Docs\non: push\n"},
	}
	for _, tc := range cases {
		final := guide.AddMarker(tc.kind, tc.src, []byte(tc.body))
		if !strings.HasSuffix(string(final), "\n") || strings.HasSuffix(string(final), "\n\n") {
			t.Errorf("marker output must end in exactly one newline: %q", final)
		}
		info, ok := guide.ParseMarker(tc.kind, final)
		if !ok || info.Src != tc.src {
			t.Fatalf("ParseMarker = %+v ok=%v, want src=%q", info, ok, tc.src)
		}
		got, ok := guide.StripMarker(tc.kind, final)
		if !ok || string(got) != tc.body {
			t.Fatalf("StripMarker round-trip:\n got %q\nwant %q", got, tc.body)
		}
	}
	if _, ok := guide.StripMarker(guide.KindMD, []byte("no marker here\n")); ok {
		t.Fatal("StripMarker must report false on a markerless file")
	}
}

func TestMarkerShebangPlacement(t *testing.T) {
	out := string(guide.AddMarker(guide.KindSH, "s.sh", []byte("#!/bin/sh\nset -e\n")))
	lines := strings.Split(out, "\n")
	if lines[0] != "#!/bin/sh" {
		t.Fatalf("line 1 = %q, want shebang", lines[0])
	}
	if !strings.HasPrefix(lines[1], "# GENERATED by cc-guides from s.sh/") {
		t.Fatalf("line 2 = %q, want marker", lines[1])
	}
}

func TestParseMarkerKindPosition(t *testing.T) {
	mdMarker := guide.MarkerLine(guide.KindMD, "x")
	shMarker := guide.MarkerLine(guide.KindSH, "x")
	ymlMarker := guide.MarkerLine(guide.KindYAML, "x")
	cases := []struct {
		name    string
		kind    guide.Kind
		content string
		want    bool
	}{
		{"md marker line 1", guide.KindMD, mdMarker + "\nbody\n", true},
		{"md marker line 3", guide.KindMD, "one\ntwo\n" + mdMarker + "\n", false},
		{"wrong-kind wrapper", guide.KindSH, mdMarker + "\nset -e\n", false},
		{"sh shebang then marker", guide.KindSH, "#!/bin/sh\n" + shMarker + "\nset -e\n", true},
		{"sh non-shebang line 1", guide.KindSH, "echo hi\n" + shMarker + "\n", false},
		{"yml marker line 1", guide.KindYAML, ymlMarker + "\nname: x\n", true},
		{"yml no shebang branch", guide.KindYAML, "#!/bin/sh\n" + ymlMarker + "\n", false},
		{"yml wrong-kind wrapper", guide.KindYAML, mdMarker + "\nname: x\n", false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if _, ok := guide.ParseMarker(tc.kind, []byte(tc.content)); ok != tc.want {
				t.Fatalf("ParseMarker ok = %v, want %v", ok, tc.want)
			}
		})
	}
}
