package guide

import (
	"bytes"
	"fmt"
	"regexp"
	"strings"
)

// MarkerCoreRegex is the stable machine contract for the version-free marker.
// It is pinned here and asserted verbatim in the tests; changing it is a
// migration. The src group captures the layout dir (without its trailing slash).
const MarkerCoreRegex = `GENERATED by cc-guides from (?P<src>\S+)/ — do not edit; edit the fragments and run 'cc-guides render'\.`

var markerCoreRe = regexp.MustCompile(MarkerCoreRegex)

// markerCoreFmt renders the marker core; the one %s is the source layout dir.
const markerCoreFmt = "GENERATED by cc-guides from %s/ — do not edit; edit the fragments and run 'cc-guides render'."

// MarkerCore returns the unwrapped marker core string for srcDir.
func MarkerCore(srcDir string) string {
	return fmt.Sprintf(markerCoreFmt, srcDir)
}

// MarkerInfo is a parsed marker. Src is the layout dir it names.
type MarkerInfo struct {
	Src string
}

// MarkerLine wraps the marker core in the comment style for kind.
func MarkerLine(kind Kind, srcDir string) string {
	core := MarkerCore(srcDir)
	switch kind {
	case KindMD:
		return "<!-- " + core + " -->"
	case KindSH, KindYAML:
		return "# " + core
	default:
		return core
	}
}

// AddMarker splices the version-free marker into composed content and returns
// bytes ending in exactly one newline. For sh content beginning with `#!`, the
// shebang stays on line 1 and the marker becomes line 2.
func AddMarker(kind Kind, srcDir string, content []byte) []byte {
	line := MarkerLine(kind, srcDir)
	body := string(content)
	var out string
	if kind == KindSH && strings.HasPrefix(body, "#!") {
		if nl := strings.IndexByte(body, '\n'); nl >= 0 {
			out = body[:nl] + "\n" + line + "\n" + body[nl+1:]
		} else {
			out = body + "\n" + line
		}
	} else {
		out = line + "\n" + body
	}
	return ensureSingleTrailingNewline([]byte(out))
}

// ParseMarker reports whether content carries a generated marker at the position
// AddMarker would have written it for kind: line 1, or line 2 only when line 1 is
// a shell shebang. A marker-shaped line anywhere else is ordinary content.
func ParseMarker(kind Kind, content []byte) (MarkerInfo, bool) {
	lines := firstLines(content, 2)
	if len(lines) == 0 {
		return MarkerInfo{}, false
	}
	if info, ok := matchMarkerLine(kind, lines[0]); ok {
		return info, true
	}
	if kind == KindSH && len(lines) >= 2 && strings.HasPrefix(lines[0], "#!") {
		if info, ok := matchMarkerLine(kind, lines[1]); ok {
			return info, true
		}
	}
	return MarkerInfo{}, false
}

// StripMarker is the inverse of AddMarker: it removes the marker line and returns
// the body, or (content, false) when no marker is present.
func StripMarker(kind Kind, content []byte) ([]byte, bool) {
	lines := firstLines(content, 2)
	if len(lines) == 0 {
		return content, false
	}
	if _, ok := matchMarkerLine(kind, lines[0]); ok {
		return afterLine(content, 0), true
	}
	if kind == KindSH && len(lines) >= 2 && strings.HasPrefix(lines[0], "#!") {
		if _, ok := matchMarkerLine(kind, lines[1]); ok {
			return append([]byte(lines[0]+"\n"), afterLine(content, 1)...), true
		}
	}
	return content, false
}

// matchMarkerLine matches the marker core within a single line AND requires the
// comment wrapper to match kind (clobber-safety over recognition): an HTML comment
// for markdown, a `# ` comment for shell. A wrong-kind wrapper is NOT recognized,
// so render/check never treats it as a clobberable generated file.
func matchMarkerLine(kind Kind, line string) (MarkerInfo, bool) {
	m := markerCoreRe.FindStringSubmatch(line)
	if m == nil {
		return MarkerInfo{}, false
	}
	switch kind {
	case KindMD:
		if !strings.HasPrefix(line, "<!--") {
			return MarkerInfo{}, false
		}
	case KindSH, KindYAML:
		if !strings.HasPrefix(line, "# ") {
			return MarkerInfo{}, false
		}
	}
	return MarkerInfo{Src: m[1]}, true
}

// afterLine returns the content following line index n (0-based), i.e. everything
// after the (n+1)-th newline.
func afterLine(content []byte, n int) []byte {
	rest := content
	for i := 0; i <= n; i++ {
		idx := bytes.IndexByte(rest, '\n')
		if idx < 0 {
			return nil
		}
		rest = rest[idx+1:]
	}
	return rest
}

func firstLines(content []byte, n int) []string {
	var out []string
	rest := content
	for i := 0; i < n; i++ {
		idx := bytes.IndexByte(rest, '\n')
		if idx < 0 {
			if len(rest) > 0 {
				out = append(out, string(rest))
			}
			break
		}
		out = append(out, string(rest[:idx]))
		rest = rest[idx+1:]
	}
	return out
}

// ensureSingleTrailingNewline collapses trailing newlines to exactly one.
func ensureSingleTrailingNewline(b []byte) []byte {
	b = bytes.TrimRight(b, "\n")
	return append(b, '\n')
}
