package guide_test

import (
	"errors"
	"strings"
	"testing"

	"github.com/yasyf/cc-guides/guide"
)

// The toml marker is the shell `# ` comment form, exact — same syntax as sh/yml.
func TestTOMLMarkerExact(t *testing.T) {
	got := guide.MarkerLine(guide.KindTOML, "x")
	want := "# GENERATED by cc-guides from x/ — do not edit; edit the fragments and run 'cc-guides render'."
	if got != want {
		t.Fatalf("toml marker = %q, want %q", got, want)
	}
}

// AddMarker / ParseMarker / StripMarker round-trip on a toml body: no shebang branch,
// so the marker is line 1 and strips cleanly, and the src round-trips.
func TestTOMLMarkerAddParseStripRoundTrip(t *testing.T) {
	cases := []struct {
		src  string
		body string
	}{
		{".claude/fragments/.claude/capt-hook.toml", "[packs.general]\nsource = \"builtin\"\n"},
		{".claude/fragments/x.toml", "# a load-bearing comment\n[tool]\nkey = \"value\"\n"},
	}
	for _, tc := range cases {
		final := guide.AddMarker(guide.KindTOML, tc.src, []byte(tc.body))
		if !strings.HasSuffix(string(final), "\n") || strings.HasSuffix(string(final), "\n\n") {
			t.Errorf("marker output must end in exactly one newline: %q", final)
		}
		if !strings.HasPrefix(string(final), guide.MarkerLine(guide.KindTOML, tc.src)+"\n") {
			t.Fatalf("toml marker must lead line 1: %q", final)
		}
		info, ok := guide.ParseMarker(guide.KindTOML, final)
		if !ok || info.Src != tc.src {
			t.Fatalf("ParseMarker = %+v ok=%v, want src=%q", info, ok, tc.src)
		}
		got, ok := guide.StripMarker(guide.KindTOML, final)
		if !ok || string(got) != tc.body {
			t.Fatalf("StripMarker round-trip:\n got %q\nwant %q", got, tc.body)
		}
	}
}

// The marker wrapper is kind-checked (clobber-safety over recognition): a `# `-form
// marker is recognized for toml, an md `<!-- -->` marker is not, and — toml having no
// shebang branch — a marker past line 1 is ordinary content.
func TestTOMLParseMarkerKindPosition(t *testing.T) {
	tomlMarker := guide.MarkerLine(guide.KindTOML, "x")
	mdMarker := guide.MarkerLine(guide.KindMD, "x")
	cases := []struct {
		name    string
		content string
		want    bool
	}{
		{"toml marker line 1", tomlMarker + "\n[t]\n", true},
		{"toml marker line 2 not matched", "[t]\n" + tomlMarker + "\n", false},
		{"wrong-kind wrapper", mdMarker + "\n[t]\n", false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if _, ok := guide.ParseMarker(guide.KindTOML, []byte(tc.content)); ok != tc.want {
				t.Fatalf("ParseMarker ok = %v, want %v", ok, tc.want)
			}
		})
	}
}

// A toml artifact concatenates disjoint table sets like yaml (one blank line between
// pieces, never a semantic merge), so comments survive verbatim and the concatenation
// is itself valid TOML.
func TestComposeTOML(t *testing.T) {
	pieces := []guide.Piece{
		{Body: []byte("# fixes: the safety pack\n[packs.fixes]\nsource = \"builtin\"\n"), Origin: "base.toml"},
		{Body: []byte("[packs.go]\nsource = \"builtin\"\n"), Origin: "go.toml"},
	}
	got, err := guide.Compose(guide.KindTOML, pieces)
	if err != nil {
		t.Fatal(err)
	}
	want := "# fixes: the safety pack\n[packs.fixes]\nsource = \"builtin\"\n\n[packs.go]\nsource = \"builtin\"\n"
	if string(got) != want {
		t.Fatalf("toml compose =\n%q\nwant\n%q", got, want)
	}
	if err := guide.KindTOML.PostComposeValidate(got); err != nil {
		t.Fatalf("disjoint-table compose must post-compose-validate clean: %v", err)
	}
}

// Post-compose validation catches the authoring mistake two individually-valid
// fragments create: the same table defined in both. The composition (a byte concat)
// still succeeds; the validation names the offending table.
func TestTOMLPostComposeDuplicateTable(t *testing.T) {
	for _, body := range [][]byte{
		[]byte("[packs.general]\nsource = \"builtin\"\n"),
		[]byte("[packs.general]\nsource = \"other\"\n"),
	} {
		if err := guide.LintTOML(body); err != nil {
			t.Fatalf("each fragment must be valid TOML alone: %v", err)
		}
	}
	pieces := []guide.Piece{
		{Body: []byte("[packs.general]\nsource = \"builtin\"\n"), Origin: "a.toml"},
		{Body: []byte("[packs.general]\nsource = \"other\"\n"), Origin: "b.toml"},
	}
	composed, err := guide.Compose(guide.KindTOML, pieces)
	if err != nil {
		t.Fatalf("compose is a byte concat and must succeed: %v", err)
	}
	err = guide.KindTOML.PostComposeValidate(composed)
	if err == nil {
		t.Fatal("duplicate table across fragments must fail post-compose validation")
	}
	if !errors.Is(err, guide.ErrTOMLDecode) {
		t.Fatalf("err = %v, want ErrTOMLDecode", err)
	}
	if !strings.Contains(err.Error(), "packs.general") {
		t.Fatalf("error must name the offending table, got %q", err)
	}
}

// Distinct {{token}} placeholders in table-header position neutralize to distinct
// numeric literals, so a legitimately-templated pair of tables is not read as a false
// duplicate — while the same token twice is still a genuine duplicate that fails.
func TestLintTOMLDistinctTokens(t *testing.T) {
	if err := guide.LintTOML([]byte("[packs.{{first}}]\nsource = \"builtin\"\n[packs.{{second}}]\nsource = \"other\"\n")); err != nil {
		t.Fatalf("distinct-token tables must lint clean, got %v", err)
	}
	if err := guide.LintTOML([]byte("[packs.{{a}}]\nx = 1\n[packs.{{a}}]\ny = 2\n")); !errors.Is(err, guide.ErrTOMLDecode) {
		t.Fatalf("the same token twice must still fail as a duplicate table, got %v", err)
	}
	// A literal numeric table (here [packs.1000]) alongside a {{token}} table must NOT
	// read as a duplicate: the token neutralizes to the smallest integer >= 1000 that is
	// not a literal in the body (1001, since 1000 is present), so the tables stay distinct.
	if err := guide.LintTOML([]byte("[packs.1000]\nx = 1\n[packs.{{first}}]\nsource = \"builtin\"\n")); err != nil {
		t.Fatalf("a literal [packs.1000] plus a token table must lint clean, got %v", err)
	}
}

// A TOML fragment after the first must open with a [table] header, because TOML table
// context persists across the concatenation boundary: a later fragment's bare root-level
// key would be silently re-scoped into the preceding fragment's trailing table. The
// first fragment may open with root-level keys.
func TestComposeTOMLTableFirst(t *testing.T) {
	rootFirst := guide.Piece{Body: []byte("schema = 1\n[packs.general]\nsource = \"builtin\"\n"), Origin: "first.toml"}
	tableSecond := guide.Piece{Body: []byte("[packs.go]\nsource = \"builtin\"\n"), Origin: "second.toml"}
	rootSecond := guide.Piece{Body: []byte("# a comment\nsource = \"leaked\"\n"), Origin: "bad.toml"}

	// First fragment with root keys, second opening with a table: composes cleanly.
	if _, err := guide.Compose(guide.KindTOML, []guide.Piece{rootFirst, tableSecond}); err != nil {
		t.Fatalf("root-key first + table-led second must compose: %v", err)
	}
	// Second fragment opening (past comments) with a bare root-level key: rejected,
	// naming the offending fragment.
	_, err := guide.Compose(guide.KindTOML, []guide.Piece{tableSecond, rootSecond})
	if !errors.Is(err, guide.ErrTOMLRootKey) {
		t.Fatalf("bare-root-key second fragment must fail with ErrTOMLRootKey, got %v", err)
	}
	if !strings.Contains(err.Error(), "bad.toml") {
		t.Fatalf("error must name the offending fragment, got %q", err)
	}
	// A header preceded by a vertical tab — whitespace TOML forbids as indentation, so not
	// a real opener — is not recognized as the fragment's [table] header and is rejected.
	vtabSecond := guide.Piece{Body: []byte("\v[packs.go]\nsource = \"builtin\"\n"), Origin: "vtab.toml"}
	if _, err := guide.Compose(guide.KindTOML, []guide.Piece{tableSecond, vtabSecond}); !errors.Is(err, guide.ErrTOMLRootKey) {
		t.Fatalf("a vertical-tab-indented header must fail with ErrTOMLRootKey, got %v", err)
	}
	cases := []struct {
		name    string
		second  guide.Piece
		want    string
		wantErr error
	}{
		// Accepted delta: a malformed non-first fragment fails ErrTOMLRootKey at the
		// opener — before decode, and before any token-mismatch error.
		{
			name:    "malformed fragment",
			second:  guide.Piece{Body: []byte("[not closed\n"), Origin: "broken.toml"},
			wantErr: guide.ErrTOMLRootKey,
		},
		{
			name: "tokenized opener",
			second: guide.Piece{
				Body:   []byte("[packs.{{name}}]\nsource = \"x\"\n"),
				Args:   map[string]string{"name": "templated"},
				Keys:   []string{"name"},
				Origin: "token.toml",
			},
			want: "[packs.go]\nsource = \"builtin\"\n\n[packs.templated]\nsource = \"x\"\n",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := guide.Compose(guide.KindTOML, []guide.Piece{tableSecond, tc.second})
			if tc.wantErr != nil {
				if !errors.Is(err, tc.wantErr) {
					t.Fatalf("err = %v, want %v", err, tc.wantErr)
				}
				return
			}
			if err != nil {
				t.Fatal(err)
			}
			if string(got) != tc.want {
				t.Fatalf("compose = %q, want %q", got, tc.want)
			}
		})
	}
}

// STEWARDSHIP: a `%YAML 1.2` directive fragment that old render accepted is now rejected
// by post-compose YAML validation (yaml.v3 rejects it as an incompatible document). This
// is intended fail-fast — zero fleet usage, and lint already rejected it — pinned so the
// decision is recorded.
func TestYAMLDirectiveRejectedPostCompose(t *testing.T) {
	if err := guide.KindYAML.PostComposeValidate([]byte("%YAML 1.2\n---\nname: x\n")); !errors.Is(err, guide.ErrYAMLParse) {
		t.Fatalf("a %%YAML 1.2 directive must fail post-compose YAML validation, got %v", err)
	}
}

// A legitimately mustache-templated shell fragment passes sh lint: each {{token}} is
// neutralized to its bare name (a valid bash word) before the tree-sitter-bash syntax
// parse. A genuinely malformed fragment still fails, and a GitHub-Actions ${{ … }}
// expression — a declared, intended exception that does not match the token regex — is
// left verbatim and still fails, pinned so the decision is recorded.
func TestSHLintMustacheTokens(t *testing.T) {
	if vs := guide.KindSH.Lint([]byte("#!/bin/sh\n{{binary}} --version\n")); len(vs) != 0 {
		t.Fatalf("a mustache-templated shell fragment must lint clean, got %v", vs)
	}
	if vs := guide.KindSH.Lint([]byte("#!/bin/sh\necho 'unterminated\n")); len(vs) == 0 {
		t.Fatal("a malformed shell fragment must still fail sh lint")
	}
	if vs := guide.KindSH.Lint([]byte("#!/bin/sh\necho \"${{ github.run_number }}\"\n")); len(vs) == 0 {
		t.Fatal("a GitHub-Actions ${{ … }} expression in a shell fragment must still fail sh lint")
	}
}

// {{token}} placeholders are tolerated by the toml validators (neutralized to a
// scalar), in a value or a whole-scalar position — a real substitution runs at
// compose time — while genuinely malformed TOML still fails.
func TestLintTOMLTokens(t *testing.T) {
	for _, body := range []string{
		"[tool]\nname = \"{{binary}}\"\n",
		"[tool]\ncount = {{n}}\n",
	} {
		if err := guide.LintTOML([]byte(body)); err != nil {
			t.Fatalf("token toml must lint clean: %q: %v", body, err)
		}
	}
	if err := guide.LintTOML([]byte("[tool\nx = 1\n")); !errors.Is(err, guide.ErrTOMLDecode) {
		t.Fatalf("malformed toml err = %v, want ErrTOMLDecode", err)
	}
}

// yml also gains post-compose validation: two fragments each valid YAML that compose
// to a duplicate top-level key fail at render (yaml.v3 rejects duplicate keys).
func TestYAMLPostComposeDuplicateKey(t *testing.T) {
	pieces := []guide.Piece{
		{Body: []byte("name: CI\non: push\n"), Origin: "a.yml"},
		{Body: []byte("name: Other\n"), Origin: "b.yml"},
	}
	composed, err := guide.Compose(guide.KindYAML, pieces)
	if err != nil {
		t.Fatal(err)
	}
	if err := guide.KindYAML.PostComposeValidate(composed); err == nil {
		t.Fatal("duplicate top-level key across yaml fragments must fail post-compose validation")
	}
}

// Post-compose validation is gated to the semantic (cross-fragment) check on Append
// kinds: sh (no semantic validator) is exempt — a composed shell artifact legitimately
// carries GitHub-Actions ${{ … }} expressions that tree-sitter-bash rejects but must
// render verbatim — and a Merge kind (JSON) is validated by its own codec, and md by
// neither.
func TestPostComposeExemptions(t *testing.T) {
	sh := []byte("#!/bin/sh\necho ${{ github.run_number }}\nRUN=${{ matrix.os }}\n")
	if err := guide.KindSH.PostComposeValidate(sh); err != nil {
		t.Fatalf("sh must be exempt from post-compose validation, got %v", err)
	}
	if err := guide.KindJSON.PostComposeValidate([]byte("not json { { {")); err != nil {
		t.Fatalf("merge kind (JSON) must be exempt from post-compose validation, got %v", err)
	}
	if err := guide.KindMD.PostComposeValidate([]byte("# anything at all\n")); err != nil {
		t.Fatalf("md must be exempt, got %v", err)
	}
}
